### ISSUE TITLE
Dependency not listed: recode

### ISSUE THREAD

**Issue by Kuuhhl** [Bugswriter/tuxi#1]
Hey, 
when trying out the tool, I noticed it requires the package 'recode', which is not listed.
Can you add it to the requirements?

**Comment by Bugswriter** [comment]
Yes

**Comment by Kuuhhl** [comment]
Solved.

**Comment by andrewboldi** [comment]
Hi is there an easy way to install the recode package? I am attempting to install it from (https://github.com/rrthomas/recode)[here] but there are 13 dependencies which recode is having issues with. Any tips?
