### ISSUE TITLE
Shebang line

### ISSUE THREAD

**Issue by handejong** [Bugswriter/tuxi#10]
Hey Bugswriter,

Awesome package, works like a charm. Really cool idea. I have a short question. For me to get this to work on my Ubuntu system, I had to change the shebang from
```bash
#!/bin/sh
```
to one of these two:
```bash
#!/bin/bash
#!/usr/bin/env bash
```
I'm not completely clear why this is. Curious to learn though.

-Han

**Comment by rizaumami** [comment]
Because it's uses `[[` which is bashism.

**Comment by BachoSeven** [comment]
Indeed. #5 fixes this issue.
