### ISSUE TITLE
[Bug] Another issue with #81

### ISSUE THREAD

**Issue by Bugswriter** [Bugswriter/tuxi#102]
Instead of getting ...information about Wandavision

![image](https://user-images.githubusercontent.com/23283318/108492966-c4c36780-72cb-11eb-9777-68e2bc106332.png)

I am getting list of episodes
This is because in https://github.com/Bugswriter/tuxi/pull/81 (@d-shaun )
This is the only thing we able to fetch from here -

![image](https://user-images.githubusercontent.com/23283318/108493535-72cf1180-72cc-11eb-9c32-cca7fe2e6a67.png)

This is happening because .. Tuxi is unable to scrape information. Which tuxi should
When I do same thing for game of thrones - 

![image](https://user-images.githubusercontent.com/23283318/108493769-b88bda00-72cc-11eb-86a6-8a9ef8530747.png)

So we have info but we are getting in one case but not getting in another. ?? may be classname is different in both these cases.

**Comment by d-shaun** [comment]
I saw scraping the rich list as a really cool addition, but I see it's mostly only causing issues kekw. I guess moving the knowledge box (?) extraction before rich list might fix this?

**Comment by Bugswriter** [comment]
But we are getting nothing from knowledge box.. This is why tuxi is showing episodes list which you added.
The question is why we are getting knowledge box for Game of thrones but not for wanda vision?

**Comment by Genghius** [comment]
this can be solved by prioritizing rich lists below kno_top and kno_rigth

**Comment by Bugswriter** [comment]
> this can be solved by prioritizing rich lists below kno_top and kno_rigth

question why this is not happening for game of thrones?

**Comment by Genghius** [comment]
this cannot be solved, rich lists break everything. i put them at the bottom with a hard fix for #103 in my latest PR but that wont solve all problems, i recomend removing rich lists.

**Comment by Bugswriter** [comment]
We already did. removed rich lists. IG @colonvirus last night ..managed to make lists properly.

**Comment by Genghius** [comment]
then #107 is using an old version and has massive conflicts left and rigth.
