### ISSUE TITLE
Output missing for specific question

### ISSUE THREAD

**Issue by Nisc3d** [Bugswriter/tuxi#106]
- `shell` bash
- `Operating system/version`: Arch
- `Terminal name/version`: konsole 20.12.2
- `$TERM`

## Steps to Reproduce the Problem

Write the question "ist windows besser als Mac"

## Expected Behavior

It should output this text:
![grafik](https://user-images.githubusercontent.com/7361310/108496570-88334400-72aa-11eb-8b49-213a44c2679f.png)

## Actual Behavior

![grafik](https://user-images.githubusercontent.com/7361310/108496643-a600a900-72aa-11eb-936d-08fabb359020.png)

**Comment by Bugswriter** [comment]
Which language and location?

**Comment by Genghius** [comment]
![image](https://user-images.githubusercontent.com/62076069/108500040-1ad1e400-72a7-11eb-9765-65c98a0e5926.png)
i cant replicate it, but i can guess that the issue is caused by that formated text at the start of that div.

**Comment by Nisc3d** [comment]
> Which language and location?

This is German and I am in Germany.

**Comment by Genghius** [comment]
Is it only with this very specific querry or have you managed to replicate it in multiple other querries?

**Comment by Nisc3d** [comment]
I noticed it only with this query.

**Comment by Nisc3d** [comment]
> ![image](https://user-images.githubusercontent.com/62076069/108500040-1ad1e400-72a7-11eb-9765-65c98a0e5926.png)
> i cant replicate it, but i can guess that the issue is caused by that formated text at the start of that div.

The result you get is different from my result btw.

**Comment by Genghius** [comment]
I see. then its an issue for whomever handless formatting.

**Comment by Genghius** [comment]
this issue is from before we added language options to tuxi right? have you tried running this same querry with language set to the same as the querry?

**Comment by Nisc3d** [comment]
It works now. I think I can close this.
