### ISSUE TITLE
Encoding trouble

### ISSUE THREAD

**Issue by dadyarri** [Bugswriter/tuxi#11]
I have non-latin localization on my machine. Tuxi outputs this thing:

```
> tuxi linus torvalds birthday
28 Ð´ÐµÐºÐ°Ð±ÑÑ 1969 Ð³.
```

Fixed with forcing english language in curl:

```bash
webpage=$(curl -s -G "https://www.google.com/search?hl=en_US" --user-agent "$user_agent" --data-urlencode "q=$query")
```

**Comment by Bugswriter** [comment]
it's fixed now. Closing.

**Comment by JStyle21** [comment]
I think i have a similar problem since i'm seeing this:
`
tuxi elon musk age
49Â years
`

I'm still debugging this, just wanted to update
