### ISSUE TITLE
[Suggestion] Give an option to Open google in browser

### ISSUE THREAD

**Issue by jhagas** [Bugswriter/tuxi#114]
Adding more new feature seems to mess up with current feature. And only the user that know what features must be prioritized more than the others
So it's beneficial to just open browser everytime the script gets no result (it also saves time btw)

**Comment by BeyondMagic** [comment]
Open browser if there's an option enabled, by default it should only give the link. Becaude typos shouldn't open a browser.

**Comment by jhagas** [comment]
Okay, it makes sense

**Comment by Bugswriter** [comment]
Why? you can google directly in browser.

**Comment by BeyondMagic** [comment]
Well, tbh, tuxi was made with one of its goals to avoid opening browsers, but you can easily make a function in your shell rc and use the same arguments to open your browser with google when tuxi returns "No result".
