### ISSUE TITLE
is this can use in windows?

### ISSUE THREAD

**Issue by aow73320** [Bugswriter/tuxi#115]
ha is this have windows version?

**Comment by jhagas** [comment]
It is written in POSIX compliant shell, so you can run it in windows by using WSL

https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by aow73320** [comment]
@jhagas thank you very much!

**Comment by Bugswriter** [comment]
No

**Comment by Genghius** [comment]
This is on the level of someone that goes to a desert with a bottle of water, gets lost, pours the bottle in the sand.
Use Cortana.
