### ISSUE TITLE
Can't search for word meanings...

### ISSUE THREAD

**Issue by Prayag2** [Bugswriter/tuxi#118]
- `shell`: fish shell
- `Operating system/version`: Manjaro KDE
- `Terminal name/version`: Konsole
- `$TERM`

## Steps to Reproduce the Problem

- Search for "meaning of [word]" and you will get "no result"

## Expected Behavior

Expected it to tell me the meaning of that word.

## Actual Behavior

Getting "no result"

## Log

No warnings...

## Screenshot
![SS_2021-02-20_21-44-04](https://user-images.githubusercontent.com/39525869/108601932-44812d00-73c5-11eb-965f-a7da2177bef6.png)

**Comment by Bugswriter** [comment]
We added a define feature in our working branch. You will get update for this soon.

**Comment by Genghius** [comment]
someone put rich answers above definitions again.
