### ISSUE TITLE
Not Running!

### ISSUE THREAD

**Issue by YediPublic** [Bugswriter/tuxi#125]
Installed as showed, but it says "pup" not found! when typing tuxi -h in stterm. What should i do? Running Ubuntu 18.04 with i3wm

**Comment by sudocanttype** [comment]
Uhhhhhhh install pup. Look at the requirements in the README. also check out this link https://github.com/ericchiang/pup

**Comment by sudocanttype** [comment]
Also guys, we should make it so that if it doesn't find a necessary dependency, it helps link them to it.

**Comment by sudocanttype** [comment]
`        if [ ! "$(command -v $1)" ]; then
            error_msg "\"$1\" not found!"
            printf "Check out the dependencies at https://github.com/Bugswriter/tuxi#requirements"
`
Something like this would be the easy way to do it, except I refuse to touch formatting in bash strings because I'm bad at it

**Comment by Genghius** [comment]
have you considered switching to windows and using cortana?

**Comment by Genghius** [comment]
xd, actually all you have to do is install the dependencies needed by tuxi, we linked them all in the README

**Comment by sudocanttype** [comment]
> have you considered switching to windows and using cortana?

oof, brutal

**Comment by Bugswriter** [comment]
This guy install pup in his video -
https://www.youtube.com/watch?v=bPdq1ntXHBs
use substitles translation to english
@Genghius @sudocanttype you also watch it. It's on tuxi.

**Comment by sudocanttype** [comment]
Huh. That's really cool that someone made a video detailing the installation steps
