### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by select** [Bugswriter/tuxi#126]
Hey thanks for your project. I saw it and build my own project inspired by your code.

https://gitlab.com/s3lect/taavi-bot

**Comment by Bugswriter** [comment]
yeah it's cool.
But why you think your project is a issue for us?

Glad to tuxi is becoming a way to integrate into small assistants.

**Comment by Bugswriter** [comment]
BTW we have a huge improvement in list . . in develop branch ..soon you can have that in your bot.

**Comment by select** [comment]
Nice, I already updated my bot with some of your changes. I will check back from time to time and integrate your changes
