### ISSUE TITLE
Porting list feature from develop to main

### ISSUE THREAD

**Issue by Bugswriter** [Bugswriter/tuxi#127]
Now if you guys don't remember we have some high quality list view in our develop branch. and in our current main branch
list view have a bug of that secondary text. Someone opened a issue for that. and we closed it coz we fixed that in develop.

Right now we are unable to get list in our main -
tuxi list of linux distros 

issue with develop branch list.
Develop branch list is able to grap episodes list. and in those episodes list. The issue is sometimes when we search for some 
tv show we get list instead of just basic information .. 
Because list have more priority than knowledge (right). 
in wanda vision I was getting episodes list but in game of thrones I was not getting list I was getting information.

So we need to solve this and port good version of lists from develop to main.

**Comment by Genghius** [comment]
the rich lists in develop branch are good.
lets ask whoever wrote them to try and get them working in main without breaking everything.

**Comment by Bugswriter** [comment]
Why I guess I can just copy the code and add it in main or a fork of main. The only issue is .. that wanda vision one which I  mentioned in .. top

**Comment by BeyondMagic** [comment]
I think it was me [who wrote it](https://github.com/Bugswriter/tuxi/issues/91#issuecomment-781713961), I can fix that again, but right now I think I can optimize the code, so I'll open a PR for that.

**Comment by BeyondMagic** [comment]
This issue doesn't seem high priority, but the @PureArtistry's branch have all it fixed, waiting until it merges to the main seems a better idea.
