### ISSUE TITLE
Does not work with Tor.

### ISSUE THREAD

**Issue by userdoesnothasaname** [Bugswriter/tuxi#128]
It does not work with tor as when direct search with google when routed through tor, google asks for human verification.
Working well with vpn.

**Comment by Genghius** [comment]
sadly enough we can't implement an AI system capable of bypassing captchas yet.

**Comment by Bugswriter** [comment]
Do tor network require captcha? Then it's not possible ..tell us if you get same issue with VPN/proxy.
