### ISSUE TITLE
potential script optimization

### ISSUE THREAD

**Issue by PureArtistry** [Bugswriter/tuxi#131]
First off, must say, I love the script! It's super useful, especially fun combining it with other stuff like:

![scrot_20210222-032138](https://user-images.githubusercontent.com/53883649/108652814-ef284700-74bc-11eb-80dd-807ca0a52786.png)

or pasting the results straight into a vim buffer with ```:r ! tuxi search term```

Anyway this isn't really an issue per se, I wasn't sure if I should just send a PR for this or not.
I wanted to see if I could speed the script up a bit and while my version isn't always as fast at printing the top priority answers, it generally pops out faster results.
Due to the way it's coded right now it's actually faster printing all the valid answers compared to just the single answer, as it doesn't have to access storage when printing everything, single answer creates a temporary lock directory when it finds an answer.

I've also made it easier to add remove and re-order snippets, *should* be easier to maintain.
here's a link to the code: https://gist.github.com/PureArtistry/04a705ad057ce30fb9b7bfb07729f3b5

Here's the code for the tests I ran, plus the results log
[testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6019388/testoutputs.txt)

[tuxi_test.sh.txt](https://github.com/Bugswriter/tuxi/files/6019390/tuxi_test.sh.txt)

**Comment by Bugswriter** [comment]
@Genghius isn't this what we wanted? [code](https://gist.github.com/PureArtistry/04a705ad057ce30fb9b7bfb07729f3b5)
@BeyondMagic This guy turned every scrape into a independent different functions.
Awesome job @PureArtistry 
But I think we need time to first understand all the stuff you did. 
@PureArtistry can you give me a PR on a new branch I made - `purert-version`
I will merge and test it. 
You did amazing stuff.

**Comment by Bugswriter** [comment]
Also there are few things which are bugging me in your version. But I will discuss that in the PR not here.
