### ISSUE TITLE
[Feature Request] Dictionary

### ISSUE THREAD

**Issue by kdwk** [Bugswriter/tuxi#147]
Google provides a dictionary in its search results. For example, searching for 'define free' returns this:
![Screenshot from 2021-02-24 15-27-44](https://user-images.githubusercontent.com/39268094/108963309-e601ca80-76b4-11eb-9741-972d451777cc.png)

It'd be cool if Tuxi can use this dictionary to provide word definitions

**Comment by PureArtistry** [comment]
coming soon...
![scrot_20210224-074630](https://user-images.githubusercontent.com/53883649/108965010-29881480-7674-11eb-8ec5-827db135cb40.png)

**Comment by kdwk** [comment]
Ah ok thanks

**Comment by PureArtistry** [comment]
> Ah ok thanks

you're welcome, thanks for the feedback  :+1:
