### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by Brutus11111** [Bugswriter/tuxi#151]
I'd like to change the language option but it doesn't appear to be possible. It's messing with the results I'm getting.

For example:

The video on the github page shows that I can type "tuxi i love you in spanish". and that gives an output. 

My result is: No Results

The problem is that it's looking up search results in the national version of Google, which is already an annoying issue when I try to find stuff online. Is there a way to get tuxi to use USA google instead?

**Comment by Bugswriter** [comment]
Try searching same thing on google as see if you are getting something?
also are you using vpn?
@Genghius Who did the language thing?

**Comment by BeyondMagic** [comment]
> The problem is that it's looking up search results in the national version of Google, which is already an annoying issue when I try to find stuff online. Is there a way to get tuxi to use USA google instead?

Yes, the country that you live in affects Google UI. I don't think this will work, but try changing `LANG=$(echo $LANG | sed 's/\..*//')` in the script to `LANG="en_US"`

![image](https://user-images.githubusercontent.com/51831435/109197407-b669c580-777b-11eb-904e-fb453fa8be6f.png)

**Comment by Brutus11111** [comment]
I'm sorry but where do you want me to change that?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by sudocanttype** [comment]
In the tuxi file itself.

**Comment by Brutus11111** [comment]
"try changingLANG=$(echo $LANG | sed 's/\..*//')in the script toLANG="en_US""

I don't have LANG in there.

http://termbin.com/fuvtf

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by sudocanttype** [comment]
Ah, it appears you are running on a old version of tuxi

**Comment by BeyondMagic** [comment]
Update it,
```bash
$ git clone https://github.com/Bugswriter/tuxi.git && cd tuxi/
$ sudo make install
```

**Comment by Brutus11111** [comment]
Last version the AUR

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by sudocanttype** [comment]
Oh, I'm not sure how to update the AUR. @BeyondMagic  Who's in charge of that?

**Comment by BeyondMagic** [comment]
tdy, I don't have idea who that is in github, maybe this guy @tdy? Anyway, he's the maintainer.

@Brutus11111 please, install tuxi using the commands I told you.

**Comment by Brutus11111** [comment]
Ok so tip, don't use sudo, it copies to a user directory. Doing that with sudo places the file in the /root/.local/bin directory instead.

That language trick is working so far! :D

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by sudocanttype** [comment]
Niceeeeeeeee, can you close the issue?

**Comment by BeyondMagic** [comment]
> Ok so tip, don't use sudo, it copies to a user directory. Doing that with sudo places the file in the /root/.local/bin directory instead.

Yeah, I don't know who put that in the README.md, I edited the comment.

**Comment by PureArtistry** [comment]
next update on the dev branch has the ability to set your language from the command line so you can change it on the fly (so to speak)

will be uploading soon

**Comment by Genghius** [comment]
![image](https://user-images.githubusercontent.com/62076069/109352026-19d61f00-7872-11eb-81a4-89ed0f71598a.png)
line 7 of the script has this constant, just put your language betwen the quotes and that is all.

why butcher my child like this?
> > The problem is that it's looking up search results in the national version of Google, which is already an annoying issue when I try to find stuff online. Is there a way to get tuxi to use USA google instead?
> 
> Yes, the country that you live in affects Google UI. I don't think this will work, but try changing `LANG=$(echo $LANG | sed 's/\..*//')` in the script to `LANG="en_US"`
> 
> ![image](https://user-images.githubusercontent.com/51831435/109197407-b669c580-777b-11eb-904e-fb453fa8be6f.png)

**Comment by BeyondMagic** [comment]
@Bugswriter this can be closed
