### ISSUE TITLE
weather function occasionally fails in US

### ISSUE THREAD

**Issue by sudocanttype** [Bugswriter/tuxi#160]
- Fish
- Mint
- US
- xterm-256color

## Steps to Reproduce the Problem

The test script fails on random while testing weather, and when I was testing it. 
![image](https://user-images.githubusercontent.com/61509416/109446205-d5c85300-7a06-11eb-9aed-a99fcb90c492.png)

## Expected Behavior

It to return the weather

## Actual Behavior

Look at the picture

## Log

No Log

**Comment by BeyondMagic** [comment]
main?

**Comment by sudocanttype** [comment]
Yep, and lemme get you the testoutput. It seems to be a very rare error, but still a bug.

**Comment by BeyondMagic** [comment]
Did the class scrapping changed after fixing the ºC and ºF bug?

**Comment by sudocanttype** [comment]
I am not sure, I thought they just improved the regex/filtering

**Comment by BeyondMagic** [comment]
Can you comment the lines of the new scrapping lines for weather, 205-211 and uncomment 204, and try it again? Even though it will show ºC and ºF swapped.

**Comment by sudocanttype** [comment]
Yep, still failed.
![image](https://user-images.githubusercontent.com/61509416/109447747-f940cd00-7a09-11eb-8a9b-6a44e6b036cf.png)

**Comment by BeyondMagic** [comment]
Then it's a problem with Google UI returning you those results, get the query that normally fails and instead of passing the results to tuxi to scrap, debug it to a file. Can you do it?

**Comment by BeyondMagic** [comment]
Comment line 156 and add in the next one ```curl -Gs --compressed "$google_url" --user-agent "$user_agent" --data-urlencode "q=$query" > output.html```

**Comment by sudocanttype** [comment]
Strange. It looks like it just doesnt load some times for me. 
[output.txt](https://github.com/Bugswriter/tuxi/files/6059255/output.txt)

**Comment by BeyondMagic** [comment]
soooo this can be either `curl` failing rarely to get Google's html data, or Google giving you just this result because they're trolling you, I don't think there's a solution for that since the html file that you gave doesn't give any information at all

can be just javascript trying to load the information in (question of milliseconds) and curl already exporting the data, well

# ヾ(_ _。）

**Comment by sudocanttype** [comment]
Yep, it's not a problem until someone else reports it. I'm going to assume its just a me thing and close this.
