### ISSUE TITLE
Please provide a docker container

### ISSUE THREAD

**Issue by anki-code** [Bugswriter/tuxi#161]
Hi! 

This tool looks great but I can't try it because it requires dependencies that I can't install now. Also the README has no complete instruction of installing dependencies.

Please provide a `Dockerfile` or dockerhub docker container that I can run i.e. `docker run -it tuxi Hello world`.

Thanks!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
#34

**Comment by anki-code** [comment]
There is a Python port of tuxi - https://github.com/h4de5/tuxi/blob/python-port/tuxi.py

```bash
cd /tmp
wget https://raw.githubusercontent.com/h4de5/tuxi/python-port/tuxi.py
python tuxi.py Hello world
```

**Comment by BeyondMagic** [comment]
Alright, just to note for future users searching this issue.

----

> This tool looks great but I can't try it because it requires dependencies that I can't install now

I don't know which way you tried to install them, but two of the three have ready binaries from their respective **github release** pages, so you just need to build one (recode) and put whatever you want to.

> Please provide a Dockerfile or dockerhub docker container that I can run i.e. docker run -it tuxi Hello world

**tuxi** is a single shell script with three dependencies, as far as I am aware, most of the distros that have dockers builtin normally give you already a whole tutorial of it for programs. This, obviously, gives more one file to maintain for many of us that don't even use dockers; you (reader) could contribute for the project making one and actively maintaining it, this would help future users.
