### ISSUE TITLE
Weird pup-related error

### ISSUE THREAD

**Issue by albertlunde123** [Bugswriter/tuxi#165]
Hey! I am experiencing an error that is beyond my comprehension. I am a noob so please be gentle
with me :)
I hope you can help, the program looks awesome!

- `shell` zsh
- `Operating system/version`: Ubuntu 20.04
- `Terminal name/version`: Urxvt

## Steps to Reproduce the Problem

I just followed the install wiki

## Expected Behavior

print results

## Actual Behavior

prints following error, whenever I run any command,

tuxi "i love you in danish"

Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'a.gL9Hy > b text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'span.qv3Wpe text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div.dAassd json{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div.zCubwf text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div.XcVN5d text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'span.hgKElc text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div.bbVIQb text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'span[jsname="YS01Ge"] text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div.UQt4rd json{}'.
parse error: Invalid numeric literal at line 1, column 6
---
Usage: pup [OPTIONS] COMMAND [ARGS]...

  Pluggable Micro Packager.

Options:
  --version                       Show the version and exit.
  --log-level [CRITICAL|ERROR|WARNING|WARN|INFO|DEBUG]
                                  [default: INFO]
  --help                          Show this message and exit.

Commands:
  package  Packages the GUI application in the given pip-installable source.

**Comment by PureArtistry** [comment]
you have a different program on your system also named pup, that is not the same pup as our script uses.

Did you download that specifically for the script or was it something already on the system?

if you did download it (install it through your package manager etc) for this then you need to uninstall that and install pup from here instead https://github.com/ericchiang/pup.

if it was already on your system, let me know please - thanks!

**Comment by albertlunde123** [comment]
This fixes my problem!
I had installed pup with pip3..

Thank you very much!
