### ISSUE TITLE
tuxi not running on PopOS 

### ISSUE THREAD

**Issue by rotkivvortep** [Bugswriter/tuxi#169]
I use PopOS. After installing all dependencies with either pip, go or apt, I tried running tuxi. A test consisting of just "tuxi" returns 
( I am running an x86_64 mashine with multiple termianls to see if that is somehow the error. I tried it on cool-retro-term, gnome-terminal and edex-ui )

`Hi, I'm Tuxi. Ask me anything!
Usage: tuxi [options] query
`
Then  I tried running "tuxi what is the date today"
It didnt really work, though, and I got this as an output
`Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'a.gL9Hy > b text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'span.qv3Wpe text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div.dAassd json{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div.zCubwf text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div.XcVN5d text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'span.hgKElc text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div.bbVIQb text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'span[jsname="YS01Ge"] text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div.UQt4rd json{}'.
parse error: Invalid numeric literal at line 1, column 6
---
Usage: pup [OPTIONS] COMMAND [ARGS]...

  Pluggable Micro Packager.

Options:
  --version                       Show the version and exit.
  --log-level [CRITICAL|ERROR|WARNING|WARN|INFO|DEBUG]
                                  [default: INFO]
  --help                          Show this message and exit.

Commands:
  package  Packages the GUI application in the given pip-installable source.
---
root@pop-os:/home/viktor/Downloads/recode-3.7.8# tuxi date today
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'a.gL9Hy > b text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'span.qv3Wpe text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div.dAassd json{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div.zCubwf text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div.XcVN5d text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'span.hgKElc text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div.bbVIQb text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'span[jsname="YS01Ge"] text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div.UQt4rd json{}'.
parse error: Invalid numeric literal at line 1, column 6
---
Usage: pup [OPTIONS] COMMAND [ARGS]...

  Pluggable Micro Packager.

Options:
  --version                       Show the version and exit.
  --log-level [CRITICAL|ERROR|WARNING|WARN|INFO|DEBUG]
                                  [default: INFO]
  --help                          Show this message and exit.

Commands:
  package  Packages the GUI application in the given pip-installable source.
---
`

I am 99% sure it is a pup error. I tried reinstalling it, but still nothing.

**Comment by BeyondMagic** [comment]
That's the wrong pup, uninstall the one you have and install this https://github.com/ericchiang/pup/releases/tag/v0.4.0.

**Comment by rotkivvortep** [comment]
Thank you for the fast response, I appriciate that. Please leave this issue if possible.

**Comment by BeyondMagic** [comment]
Hm? I'm pretty sure you don't have the correct one, can you show us the output of your current pup with `pup --help`?

**Comment by rotkivvortep** [comment]
Oh yeah, youre right. Sorry, english is not my first language. Problem not fixed thoug, sorry.  I ran "go get github.com/ericchiang/pup" and thats all. However, the error message remains the same. Can you provide me with the command to uninstall any wrong version of pup that might be interfering with this? I have go version go1.14.7 linux/amd64 btw.

**Comment by BeyondMagic** [comment]
>Can you provide me with the command to uninstall any wrong version of pup that might be interfering with this?

Yeah, did you uninstall the pup version before you install the new one with go?

The other pup you installed was with pip, right? If yes, just use `pip uninstall pup`, and then try to run `pup` from the terminal.

**Comment by rotkivvortep** [comment]
OK, I uninstalled pup with pip. At least we are done with that. Now I ran "go get github.com/ericchiang/pup". After that, however, i have the error ""pup" not found!" when running "tuxi me", or any query for that matter. Running the "go get ...." command reveals no errors. Now, I tried the example code. Running `curl -s https://news.ycombinator.com/ | pup 'table table tr:nth-last-of-type(n+2) td.title a'`, which is the example code given on the Github page. Then it gives me `bash: /usr/local/bin/pup: No such file or directory` .

**Comment by BeyondMagic** [comment]
Then pup is installed, the only problem you're having right now is with your PATH, it seems that GO is installed in a place that you can't run the program you just installed. 

Can you see if there's a folder called `go` in your home directory?

**Comment by rotkivvortep** [comment]
Oh yeah, using 'ls | grep go' there is one in my /root directory. It is /root/go. 
NB: for other PopOS users, the default directory is /root/go not /home/go.

**Comment by BeyondMagic** [comment]
You probably need to add that to your PATH, can you run the following command and see if pup works after that?

`export PATH="$PATH:/root/go"`

**Comment by rotkivvortep** [comment]
So I  did try the command. Now running tuxi, and that is without any queries, also gives me the error of '"pup" not found!'

**Comment by BeyondMagic** [comment]
All of them? You definitely want to give a look at this: https://stackoverflow.com/questions/30295146/how-can-i-install-a-package-with-go-get

If yet nothing works, just don't use go to install this, there's a reason that I gave you the releases link of pup, you can put the binary directly in your path and that will help us to figure out it.

> https://github.com/ericchiang/pup/releases/tag/v0.4.0.

Download the version of your computer,

> linux/amd64

and extract it.

**Comment by rotkivvortep** [comment]
Thanks! Will do and will edit with results! Once again, thank you so much for your help.

**Comment by BeyondMagic** [comment]
Tag me after you tried what I said: @BeyondMagic. I'll be waiting.

**Comment by BeyondMagic** [comment]
You fine, @rotkivvortep ?

**Comment by Bugswriter** [comment]
not a issue of tuxi
