### ISSUE TITLE
AUR package version, google translate doesnt work?

### ISSUE THREAD

**Issue by Genghius** [Bugswriter/tuxi#175]
can anyone recreate [this](https://youtu.be/ezqO5BTWsZc?t=557) issue and find out why it's happening?

**Comment by bugswriter** [comment]
if it's not working in AUR it means it's NOT working in main?

**Comment by bugswriter** [comment]
Brodie https://youtu.be/ezqO5BTWsZc made the video and he mentioned this .. in AUR version translate not working.

**Comment by Genghius** [comment]
could it be the aur version is not using main?

**Comment by bugswriter** [comment]
idk .. I never added any AUR or write any PKGBUILD

**Comment by BeyondMagic** [comment]
Just ask the maintainer of the package to update the package.

**Comment by PureArtistry** [comment]
just watched that Brodie video and that is deffo the old version he is using - I'm 4 minutes in a he is complaining that if there's no result it needs to show links (which the new version does do).

That aur package must be pointing to an older commit or something

**Comment by BeyondMagic** [comment]
The AUR maintainer was asked to update the package, let's just wait for now.

**Comment by Genghius** [comment]
oki, imma close this issue soon then.

**Comment by paperbenni** [comment]
![image](https://user-images.githubusercontent.com/15818888/149012334-0fd2f0c0-2fb2-4c1e-8f55-48a6c43806cb.png)
This problem is still (or again?) present on the current main and develop branch

**Comment by BeyondMagic** [comment]
Tuxi is not yet officialy deprecated, [but it is abandoned](https://github.com/Bugswriter/tuxi/issues/197).

There is [oi](https://github.com/PureArtistry/oi/) and [iris](https://github.com/iris-cli/iris) (still in development) as replacements.

I believe oi has already translation working, give it a go.
