### ISSUE TITLE
[Suggestion] Reductions?

### ISSUE THREAD

**Issue by BeyondMagic** [Bugswriter/tuxi#176]
I was thinking about some of the things that were added in the last version, and perhaps some things weren't best adding inside **tuxi** *??* I really don't know, that's why I opened this to discuss. Starting off, in the latest version, those flags were added:

```sh
  -b                    Tries to select the best answer based on keywords at the start and end of your query.
                        (experimental - eg: define WORD, SONG lyrics, PERSON quotes, weather CITY, FILM cast)
```

This is really not necessary, is it? With the lovely `-t`flag, the user is capable of getting answers fast enough, while this option will be always limited for certain type of queries, specific words in the start or end, etc.

---

```sh
  -l                    use LANG_[lang] in your query to override the language used
                        (eg: tuxi -l LANG_en_US my search query)
```

This can be removed since we have:
```sh
$ LANG=en_US tuxi "my search query"
$ # or better
$ export TUXI_LANG=pt_BR
$ tuxi "my search query"
```

---

Last, but not least, the work of @PureArtistry  is huge and wonderful, so I'm not in any way degrading those, just want to know more what you think about those as well.

*really hard to type reduction though*

**Comment by ghost** [comment]
Having a flag for the same functionality as that which is provided by an environment variables sits well with me. An environment variable can be a nice alternative, but not one everybody will perhaps want to use. Personally, I'm a fan of giving the user a _choice_.

**Comment by BeyondMagic** [comment]
I don't think there's any difference between using the tuxi's flag and tuxi's environment variable, _syntax speaking_, options are useful when we need them, do we really need a flag only for language variable? Adding a few lines of code only for that doesn't seems worthy.

**Comment by PureArtistry** [comment]
If fine with getting rid of the -b flag as it's hardly developed anyway. The point of it was to make it faster for obvious answers, if you're searching for 'weather in my city right now' it would only run the weather scrape. you're guaranteed the info you're looking for and faster.

I do concede it's not too useful right now

**Comment by Genghius** [comment]
I consider the -l flag to be useful, as people may want their tuxi scripts to use different languages than their default tuxi.
tho, -b is not something that i would notice if it got removed. UwU

**Comment by BeyondMagic** [comment]
Well, then leave `-l` alone, and `-b`can be cleaned?

**Comment by Genghius** [comment]
@Bugswriter what do u think? should `-b` stay or be removed because `-t` exists?

**Comment by bugswriter** [comment]
-b should stay.

**Comment by BeyondMagic** [comment]
Alright.
