### ISSUE TITLE
Feature Request : Add a flag to open links with given browser.

### ISSUE THREAD

**Issue by ashishbinu** [Bugswriter/tuxi#191]
It would be good if there is a flag to specify a browser to open the links. As the `-b` flag is used to do something, using `-B` for opening links with the given browser would be good.

For example : 
```
tuxi github of tuxi -B chromium
```

**Comment by bugswriter** [comment]
you don't need tuxi to do that.

**Comment by ashishbinu** [comment]
yeah true, I don't know what i was thinking while creating the issue
