### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by nfrid** [Bugswriter/tuxi#192]
- `shell`: fish
- `Operating system/version`: Manjaro (latest w/ 5.12.8 kernel)
- `Terminal name/version`: alacritty 0.8.0 w/ ligatures
- `Location`: Saint-Petersburg, Russian Federation
- `$TERM`: alacritty / tmux-256-color (no difference)

## Steps to Reproduce the Problem

use tuxi.

## Expected Behavior

get answer

## Actual Behavior

![image](https://user-images.githubusercontent.com/13046595/121877870-c221cd80-cd13-11eb-9efe-01af89d4dcee.png)

## Log

in previous section

**Comment by nfrid** [comment]
apparently, I can tell it is because Google's stupid antispam

![image](https://user-images.githubusercontent.com/13046595/121878817-d0bcb480-cd14-11eb-8d25-ce3f4ffd8fa3.png)

![image](https://user-images.githubusercontent.com/13046595/121878984-019ce980-cd15-11eb-9183-e21eaf013057.png)

any suggestions of how to prevent this?

**Comment by nfrid** [comment]
welp

**Comment by k2arim99** [comment]
sister proyect google-it is dealing with the same issue rn https://github.com/PatNeedham/google-it/issues/26
