### ISSUE TITLE
How to modify cURL request?

### ISSUE THREAD

**Issue by Kuuhhl** [Bugswriter/tuxi#2]
In your installation guide, you explained how to copy the cURL request to a file called gsearch.
I followed it step by step, but you didn't explain if I should change anything?
When copying the cURL request as is from [https://www.google.com/search?q=linux](https://www.google.com/search?q=linux), I always get the same results.

Example output:
```
[user@hostname] $ ./tuxi how tall is mount everest?
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  139k    0  139k    0     0   149k      0 --:--:-- --:--:-- --:--:--  149k
Linux is a family of open-source Unix-like operating systems based
on the Linux kernel, an operating system kernel first released
on September 17, 1991, by Linus Torvalds. Linux is typically
packaged in a Linux distribution.
```

**Comment by TheJackiMonster** [comment]
You just need to add in the `-s` parameter to make curl's output silent. Then you should only get the answer from the tuxi script without the status bar of curl's download.

**Comment by ap29600** [comment]
Hi, got the same issue. You need to modify the query, substituting "linux" with $1 and exchanging the single quotes with double quotes: `'https://www.google.com/search?q=linux'` -> `"https://www.google.com/search?q=$1"`

**Comment by Bugswriter** [comment]
Extremely sorry for this horrible installation procedure. I guess you guys figured out how to do this. I did some changes in read me now .. No one will get this issue.

**Comment by Bugswriter** [comment]
> 
> 
> In your installation guide, you explained how to copy the cURL request to a file called gsearch.
> I followed it step by step, but you didn't explain if I should change anything?
> When copying the cURL request as is from https://www.google.com/search?q=linux, I always get the same results.
> 
> Example output:
> 
> ```
> [user@hostname] $ ./tuxi how tall is mount everest?
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  139k    0  139k    0     0   149k      0 --:--:-- --:--:-- --:--:--  149k
> Linux is a family of open-source Unix-like operating systems based
> on the Linux kernel, an operating system kernel first released
> on September 17, 1991, by Linus Torvalds. Linux is typically
> packaged in a Linux distribution.
> ```

Also one more thing don't add '?' question mark in end .. without quotation. Also NO need of question mark.
