### ISSUE TITLE
Always No Result!

### ISSUE THREAD

**Issue by Roger-T800** [Bugswriter/tuxi#203]
- `shell` x-terminal-emul
- `Operating system/version`: Ubuntu 18.04.6 LTS i686
- `Terminal name/version`: lxterminal 0.3.1
- `Location`: GYE
- `$TERM`xterm-256color

## Steps to Reproduce the Problem

tuxi -d When did Linus Torvalds born ..... Or any query, all of them got "No Result!"
No Result!
> 0 answer(s) found - post curl processing time ~856 ms

TUXI_LANG='es_EC'  tuxi -d How tall is everest
No Result!
> 0 answer(s) found - post curl processing time ~851 ms

TUXI_LANG='en_US'  tuxi -d How tall is everest
No Result!
> 0 answer(s) found - post curl processing time ~875 ms
...

$ tuxi -v
tuxi dev 2.0

## Actual Behavior
An answer to any query

## Log
Added -d option. Only got timer info.

**Comment by BeyondMagic** [comment]
Please, close. [See why](https://github.com/Bugswriter/tuxi/issues/197).
