### ISSUE TITLE
Math symbol (greek alphabet) support

### ISSUE THREAD

**Issue by jhagas** [Bugswriter/tuxi#25]
- `fish`
- `Operating system/version`: Pop!_OS / 20.10
- `Terminal name/version`: Alacritty /  0.8.0-dev (73759da)
- `alacritty`

## Steps to Reproduce the Problem

Search for simple math formula (not including any fraction or root) like the area of circle formula
```tuxi formula area of circles```

## Expected Behavior

I expect it will showing result like this
```
The area of a circle is pi times the radius squared (A = π r²).
```

## Actual Behavior

But the actual result in CLI is
```
The area of a circle is pi times the radius
squared (A = Ï rÂ²).
```

**Comment by Bugswriter** [comment]
When you tested this? Try script now. With latest version and tell me are you still getting this issue??

**Comment by colonvirus** [comment]
This is the same issue as #15, and #13 fixes that

**Comment by jhagas** [comment]
#13 fixes this issue.. closed

**Comment by owl4ce** [comment]
Yes, why wouldn't anyone want to change `utf-8` with `ISO-8859-1` to this repo?

![image](https://user-images.githubusercontent.com/53987136/108224105-202b1380-716d-11eb-922e-abd6c3261dd8.png)
