### ISSUE TITLE
[Suggestion] Option to use a proxy

### ISSUE THREAD

**Issue by MithicSpirit** [Bugswriter/tuxi#27]
It would be nice to be able to route the requests through a proxy (like TOR) to further prevent tracking.

**Comment by owl4ce** [comment]
https://stackoverflow.com/questions/9445489/performing-http-requests-with-curl-using-proxy

**Comment by Bugswriter** [comment]
I have no idea. What should I do with this issue.

**Comment by colonvirus** [comment]
If you don't want google to track you, then yea.
An option for proxy could be added.

**Comment by Genghius** [comment]
I will start working on this tomorrow morning, once #39 and #40 are merged.

**Comment by Genghius** [comment]
I did some research...
![image](https://user-images.githubusercontent.com/62076069/108343133-7e8add00-71d3-11eb-91ed-12a7eb032328.png)
this is all u need to do to use curl with a proxy

**Comment by Genghius** [comment]
I think this issue can be closed as it isn't really an issue, is it?

**Comment by colonvirus** [comment]
This could be mentioned on the readme
