### ISSUE TITLE
Please provide a working docker container

### ISSUE THREAD

**Issue by h4de5** [Bugswriter/tuxi#34]
i wasted some time to get that thing up and running, but did not succeed installing the dependencies.. specially `recode` seems to have a problem. I tried to create a dockerfile based on ubuntu.

## Steps to Reproduce the Problem

follow all steps to install jq, record and pup ...

## Expected Behavior

docker run bugswriter:tuxi tuxi how far is the moon

## Actual Behavior

I am not getting that far :(

## Log

`make check` for record breaks:

    cat: Recode.body.c: No such file or directory
    make[2]: *** [Recode.c] Error 1
    Makefile:1569: recipe for target 'Recode.c' failed
    make[2]: Leaving directory '/install/recode/tests'
    Makefile:1432: recipe for target 'check-am' failed
    make[1]: *** [check-am] Error 2
    make[1]: Leaving directory '/install/recode/tests'
    Makefile:1509: recipe for target 'check-recursive' failed
    make: *** [check-recursive] Error 1

attached is my first draft on a Dockerfile, maybe someone can get it fixed 

```Dockerfile

FROM ubuntu:bionic

LABEL maintainer="h4de5@users.noreply.github.com" \
  version="0.0.1" \
  description="tuxi - is a cli assistant., pup - CLI tool for processing HTML, recode - Charset converter tool and library, jq - Command-line JSON processor"

ENV DEBIAN_FRONTEND=noninteractive \
    DEBCONF_NONINTERACTIVE_SEEN=true \
    LC_ALL=C.UTF-8 \
    LANG=C.UTF-8

RUN apt-get update && \
  apt-get -y install build-essential \
  curl \
  git \
  wget \
  python3 \
  python3-pip \
  unzip \
  automake \
  m4
  # sudo

# RUN mkdir /install
WORKDIR /install

# install python
RUN python3 --version

# install git
RUN git --version

# install go
# RUN wget -q "https://golang.org/dl/go1.16.linux-amd64.tar.gz" -O "go.linux-amd64.tar.gz" && \
#   tar -C /install -xf "go.linux-amd64.tar.gz" && \
#   export PATH=$PATH:/install/go/bin && \
#   export GOPATH=/install/go && \
#   go version

# install pup
# RUN /install/go/bin/go get github.com/ericchiang/pup && \
#   pup --version

RUN cd /install && \
  mkdir -p /install/pup && \
  wget -q "https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip" -O "pup.zip" && \
  unzip -d /install/pup pup.zip && \
  export PATH=$PATH:/install/pup && \
  pup --version

# install recode
RUN cd /install && \
  # git clone "https://github.com/rrthomas/recode.git" recode && \
  wget -q "https://github.com/rrthomas/recode/releases/download/v3.7.8/recode-3.7.8.tar.gz" -O "recode.tar.gz" && \
  tar -C /install -xzf "recode.tar.gz" && \
  mv /install/recode-3.7.8 /install/recode && \
  # export PATH=$PATH:/install/recode-3.7.8 && \
  cd /install/recode && \
  # ./bootstrap && \
  ./configure

# ---- it breaks here! --->
RUN cd /install/recode && \
  make check
RUN cd /install/recode && \
  make install
RUN export PATH=$PATH:/install/recode && \
  recode --version

# install jq
RUN cd /install && \
  mkdir -p /install/jq && \
  wget -q "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64" -O jq && \
  chmod +x /install/jq/jq && \
  export PATH=$PATH:/install/jq && \
  jq --version

# install tuxi
RUN cd /install && \
  git clone "https://github.com/Bugswriter/tuxi.git" tuxi && \
  export PATH=$PATH:/install/tuxi

VOLUME [ "/install" ]

ENTRYPOINT [ "tuxi", "--help" ]


```

**Comment by Genghius** [comment]
does a shell script really need docker?

**Comment by h4de5** [comment]
can you run that shell script?

**Comment by Genghius** [comment]
> can you run that shell script?

Yes

**Comment by h4de5** [comment]
so. what have you installed ? :)

really - I am not trying to be a jerk. I just can't make it work at all. I wanted to install it on some machines and I didn't want to go through the hassle to install jq, record and pup everytime.

**Comment by Bugswriter** [comment]
Some people were asking to rewrite this in rust .. I don't think I am going to do this. pup is must btw. also recode*

**Comment by Genghius** [comment]
if I spent an afternoon in it, I could rewrite it to only need sed and grep.

**Comment by owl4ce** [comment]
> Some people were asking to rewrite this in rust .. I don't think I am going to do this. pup is must btw. also recode*

Imagine rewriting in rust, just for a simple shellscript that didn't need to be written at low-level.

**Comment by Bugswriter** [comment]
> 
> 
> if I spent an afternoon in it, I could rewrite it to only need sed and grep.

with grep sed .. It's possible but code will get a lot complex. especially lists . . I don't think this is good idea. what's issue with installing pup? I think this script is for just normal Linux users. They can install pup. can someone explain what is the issue with installing dependencies?

**Comment by h4de5** [comment]
I think pup was fine using the commands above. but record failed - I didn't try jq.

**Comment by Genghius** [comment]
> > if I spent an afternoon in it, I could rewrite it to only need sed and grep.
> 
> with grep sed .. It's possible but code will get a lot complex. especially lists . . I don't think this is good idea. what's issue with installing pup? I think this script is for just normal Linux users. They can install pup. can someone explain what is the issue with installing dependencies?

thats why I said an afternoon, writing this without pup and jq alone would make it a helluva much larger script and unnecesarily complex.

**Comment by Genghius** [comment]
installing the dependencies for this should be quite easy too.
for pup:
`go get github.com/ericchiang/pup`
jq should be in your linux distro's package manager repos so it should be something as simple as:
`pacman -S jq`
or `apt install jq`
for recode:
```sh
git clone https://github.com/rrthomas/Recode.git
cd Recode
sh after-git.sh
./configure
make
make install
```

**Comment by owl4ce** [comment]
I don't know on other systems, but on **Gentoo/Linux** everything is there except `pup`.
If installing dependencies make this too long/complicated. I give 1000 billion percent rewrite support in rust (but I didn't write 😆 ).

**Comment by Bugswriter** [comment]
I think in a world where people install whole electron just to run balena etcher to boot USB. We are still better.

**Comment by Genghius** [comment]
> I don't know on other systems, but on **Gentoo/Linux** everything is there except `pup`.
> If installing dependencies make this too long/complicated. I give 1000 billion percent rewrite support in rust (but I didn't rewrite ).

do you have go installed?
https://packages.gentoo.org/packages/dev-lang/go
install go then run:
`go get github.com/ericchiang/pup`

**Comment by owl4ce** [comment]
> > I don't know on other systems, but on **Gentoo/Linux** everything is there except `pup`.
> > If installing dependencies make this too long/complicated. I give 1000 billion percent rewrite support in rust (but I didn't rewrite ).
> 
> do you have go installed?
> https://packages.gentoo.org/packages/dev-lang/go
> install go then run:
> `go get github.com/ericchiang/pup`

yeah, I have installed go but .. copying `pup` [binary](https://github.com/EricChiang/pup/releases/tag/v0.4.0) to $PATH is more easy.

**Comment by owl4ce** [comment]
> I think in a world where people install whole electron just to run balena etcher to boot USB. We are still better.

**HOLD MY DD 🤝**  

BTW, [`ventoy`](https://github.com/ventoy/Ventoy) is more better.

**Comment by h4de5** [comment]
;)
started to port it to python:
https://github.com/h4de5/tuxi/blob/python-port/tuxi.py


issue can be closed.

**Comment by h4de5** [comment]
Also: a very big thank you for the idea and the work in that project. i was searching for something similar to *short answers* from wolfram - https://products.wolframalpha.com/short-answers-api/documentation/ . and this projects even exceeds that capabilities.

**Comment by officialcactar** [comment]
I'll probably end up creating a golang port sometime in the future.

**Comment by h4de5** [comment]
just a small update: i pulled all changes up until today and completed the port for python:

https://github.com/h4de5/tuxi

I'll keep an eye on the progress and merge new stuff over every couple of days - but given your current velocity I can't promise to keep it up2date ;)


if you find it useful - please add a link in your readme.

**Comment by anki-code** [comment]
@h4de5 It's great! Thank you! I strongly recommend to create distinct repository and PyPi package for your port.

The Github Actions allow simple releasing the packages to the PyPi ([step by step](https://github.com/xonsh/xontrib-cookiecutter/tree/master/xontrib-%7B%7Bcookiecutter.project_slug%7D%7D#xontrib-promotion-read-and-remove-this-section)).
