### ISSUE TITLE
paragraphic results returning as null

### ISSUE THREAD

**Issue by officialcactar** [Bugswriter/tuxi#38]
---
name: paragraphic results returning as nul
about: shit broke 🅱️

---

- `zsh 5.8`
- `OpenBSD 6.8`:
- `st 0.8.4`:

## Steps to Reproduce the Problem

$ tuxi mt fuji

Expected Behavior screenshot is from my previous commit(1cf1d70) before the readability changes.

## Expected Behavior

![image](https://user-images.githubusercontent.com/70484952/108284110-370c3e80-714a-11eb-9df5-bffe6212b1a2.png)

## Actual Behavior

![image](https://user-images.githubusercontent.com/70484952/108284150-4b503b80-714a-11eb-8969-f5ff19cef050.png)

**Comment by owl4ce** [comment]
![image](https://user-images.githubusercontent.com/53987136/108285136-13341180-71b9-11eb-95d1-2241b7a9f488.png)

**Comment by Bugswriter** [comment]
wait is this happening for all searches?

**Comment by officialcactar** [comment]
> 
> 
> wait is this happening for all searches?

it seems like all searches that aren't 1 liners

**Comment by owl4ce** [comment]
also this (`a` before answer)

![image](https://user-images.githubusercontent.com/53987136/108285981-d5d08380-71ba-11eb-8d97-ef9b05ef0c25.png)

**Comment by Bugswriter** [comment]
I think I should revert this to older one. Until we found solution. I just uploaded another video on tuxi many people might go and try this. .can you guys give me best version or working copy?

**Comment by Genghius** [comment]
It's my fault, I am sorry.
The translating block would sometimes return null when no translation found, instead of returning empty.
However, this has been fixed in PR #37
If you merge my newest pr it will be fixed.

**Comment by Bugswriter** [comment]
Chill. . I reverted script to older one. Now I am making a branch you guys do stuff in that branch and after when we got complete confirmation ..then I will merge branch. Also Don't say sorry. you are doing great. I Thanked you all in my video - https://www.youtube.com/watch?v=E0J_IVrn1dg

**Comment by Bugswriter** [comment]
So now we have one develop branch. So all of our changes will go to develop branch. BTW guys you are doing great. I think you literally changed my stupid script into a really awesome program. I believe this will be something which every Linux user will install. All we have to do main .. repo. Look for any changes google do.

**Comment by officialcactar** [comment]
> Chill. . I reverted script to older one.

I think #1fd48a0 might be better. 
This is the commit that fixed the issue you were having.

**Comment by Genghius** [comment]
with my newest PR everything is fixed and issue #30 and this are solved.

**Comment by Bugswriter** [comment]
So do I revert to [1fd48a0](https://github.com/Bugswriter/tuxi/commit/1fd48a012a1e7011be92d38376cd8f3d5dc17dd9) or not?
are you sure your newest PR is ready to go?

**Comment by Genghius** [comment]
> So do I revert to [1fd48a0](https://github.com/Bugswriter/tuxi/commit/1fd48a012a1e7011be92d38376cd8f3d5dc17dd9) or not?
> are you sure your newest PR is ready to go?

![2021-02-18_00-31-30](https://user-images.githubusercontent.com/62076069/108287392-a3a32f80-7182-11eb-8e88-532451db8bd0.png)

**Comment by Bugswriter** [comment]
good but I don't see any PR request regarding this?

**Comment by Genghius** [comment]
> good but I don't see any PR request regarding this?

pr #37 
can you click this link? ^

**Comment by officialcactar** [comment]
Should I make a debugging script to test future pulls?

**Comment by Genghius** [comment]
> Should I make a debugging script to test future pulls?

please do

**Comment by Bugswriter** [comment]
Yes

> Should I make a debugging script to test future pulls?

yes

**Comment by Bugswriter** [comment]
> > good but I don't see any PR request regarding this?
> 
> pr #37
> can you click this link? ^

Sorry . . The title was makefile didn't realized you fix this in that PR.

**Comment by Genghius** [comment]
> > > good but I don't see any PR request regarding this?
> > 
> > 
> > pr #37
> > can you click this link? ^
> 
> Sorry . . The title was makefile didn't realized you fix this in that PR.

Yikes, i accidentally spammed that pr with commits so it got kinda out of context.

after this, issues #30 and #38(aka this one). Are fixed

**Comment by officialcactar** [comment]
> 
> 
> Yes
> 
> > Should I make a debugging script to test future pulls?
> 
> yes

About to get off for the day. I'll submit a PR tomorrow morning for the testing script.
