### ISSUE TITLE
[Suggestion] Adding selectors in variables on top?

### ISSUE THREAD

**Issue by Bugswriter** [Bugswriter/tuxi#46]
I see lot of pup in script.
Example - `pup '#NotFQb json{}'`
Assume `''#NotFQb json{}'` is a key. $key
should we make variable for all keys on top of the scipt? This will help us a little coping up the changes. Suppose if google did change class name .  We can easily follow and tweak variable. 
Something like this -
currency_key='#notFQb json{}' 
richanswer_key='.someclassname' ??

**Comment by colonvirus** [comment]
```
# Rich Answers ( eg: elevation of mount everest )
rich=$(echo "$google_html" | pup 'div.XcVN5d text{}' | recode html..ISO-8859-1)
[ -n "$rich" ] && output "$rich" && exit 0
```

This isn't hard to change really.
If google changes "Rich Answers"'s class,  I can just go to `# Rich Answers ...` and change it there.
This is the same as going to "richanswer_key" and changing it there.

**Comment by Bugswriter** [comment]
Yeah I also think  you are right. It's just we are adding so many new features and I believe google have more. But lets settle with this now.
