### ISSUE TITLE
[Suggestion] Improving read me with GIF and some other stuff

### ISSUE THREAD

**Issue by Bugswriter** [Bugswriter/tuxi#47]
Who have the best riced and clean looking setup? Isn't it better if we create GIF of tuxi's working including all cool features. Merge all GIF into one and Put it on top of readme? Also features checkbox? I really think this will look nice and better than our current way of showing tuxi working.

**Comment by Genghius** [comment]
![out](https://user-images.githubusercontent.com/62076069/108342659-f4db0f80-71d2-11eb-8874-475fbf187e8e.gif)
something like this?

**Comment by Bugswriter** [comment]
Yeah.. that would be perfect can you Write multiple commands showing different-2 features? I ll speed up video and create GIF

**Comment by colonvirus** [comment]
```sh
$ tuxi linux torvalds birthday
> Did you mean linus?
---
28 December 1969
---
```

```sh
$ tuxi -q linux torvalds birthday
---
28 December 1969
---
```
```sh
$ tuxi -r linux torvalds birthday
> Did you mean linus?
28 December 1969
```

```sh
$ tuxi "log(30)"
---
1.4771212547196624
---
```

```sh
$ tuxi "Vais para Cascais? em ingles"
---
Are you going to Cascais?
---

**Comment by Bugswriter** [comment]
You missed the paragraph ?? LIke tuxi unix ?

**Comment by colonvirus** [comment]
Yea that too

**Comment by Genghius** [comment]
> Yeah.. that would be perfect can you Write multiple commands showing different-2 features? I ll speed up video and create GIF

ok, ill do it.

**Comment by Bugswriter** [comment]
> > Yeah.. that would be perfect can you Write multiple commands showing different-2 features? I ll speed up video and create GIF
> 
> ok, ill do it.

Also don't clear the screen. Just keep typing commands.

**Comment by officialcactar** [comment]
@owl4ce has a pretty clean setup

**Comment by owl4ce** [comment]
> @owl4ce has a pretty clean setup

My setup is blind to orange.

**Comment by Bugswriter** [comment]
Also please make sure to add a question like this - 
> Does chocolate makes me fat 
> Do I go to hell if I tattoo
Because most people don't know Using google have this advantage, which  we can't get from any other search engine. 
tuxi is not only for straightforward questions like "what is unix"
You can also know it ..for more complex questions. like -
> tuxi will ether price rice

**Comment by owl4ce** [comment]
I'll do some record

**Comment by Genghius** [comment]
![TUXI](https://user-images.githubusercontent.com/62076069/108354649-a5501000-71e1-11eb-93af-e77c84bb87b2.gif)
seems I cant record as well as I expected.

**Comment by colonvirus** [comment]
You have to show the options too

**Comment by Genghius** [comment]
I leave that to yall, my color scheme may not be right for this.. it doesn't quite fit tuxi.

**Comment by owl4ce** [comment]
In my connection "do i go to hell if i tattoo?" don't show any result.

**Comment by Genghius** [comment]
religion-related google results vary by country.
if I don't use a VPN, it is difficult for me to find anything about Thelema for example.

**Comment by owl4ce** [comment]
Just some test, I forgot math

https://user-images.githubusercontent.com/53987136/108355323-40b2a680-721d-11eb-82d7-4bf9660dbe82.mp4

**Comment by owl4ce** [comment]
Can anyone make a complete list of question to test every parse?

**Comment by Bugswriter** [comment]
I am getting "video can't be played because the file is corrupt"

**Comment by owl4ce** [comment]
> Can anyone make a complete list of question to test every parse?

Oh I forgot to see example question in tuxi (commented)

**Comment by owl4ce** [comment]
> I am getting "video can't be played because the file is corrupt"

Playing from git browser? I will try to change to gif.

**Comment by Bugswriter** [comment]
LOL I feels like I am Directing a screen cast film in a github issue thread.

**Comment by Genghius** [comment]
```sh
tuxi "vais para cascais? em ingles"
tuxi "log(30)"
tuxi lyrics dont stop
tuxi linux trovalds birthday
tuxi "Who is linus torvalds?"
tuxi elevation of mt everest
tuxi weather now
tuxi 100 gbp to usd
tuxi 242 miles in m
tuxi the office cast
```

**Comment by Genghius** [comment]
![image](https://user-images.githubusercontent.com/62076069/108356448-0d075a80-71e4-11eb-876a-48c7a7593853.png)
DO I HEAR RICE?

**Comment by Bugswriter** [comment]
> ```shell
> tuxi "vais para cascais? em ingles"
> tuxi "log(30)"
> tuxi lyrics dont stop
> tuxi linux trovalds birthday
> tuxi "Who is linus torvalds?"
> tuxi elevation of mt everest
> tuxi weather now
> tuxi 100 gbp to usd
> tuxi 242 miles in m
> tuxi the office cast
> ```

I think .. You start with basic questions like - one word then knowledge graph right then fancy question. Then some other features like USD converation and else.

**Comment by Bugswriter** [comment]
Also please don't convert other language into english convert english into some other language so people can understand what is happening.

**Comment by Genghius** [comment]
yeah, that makes more sense.

**Comment by owl4ce** [comment]
How?
![output](https://user-images.githubusercontent.com/53987136/108359410-8b82ed00-7222-11eb-9627-9256b00a969c.gif)

**Comment by Bugswriter** [comment]
this is really good. Your system is looking beautiful.

**Comment by Bugswriter** [comment]
We should add this in read me.

**Comment by owl4ce** [comment]
> this is really good. Your system is looking beautiful.

Thank you

**Comment by owl4ce** [comment]
https://i.ibb.co/sCwYpZ8/output.gif
https://i.ibb.co/0VZncH7/output2.gif

**Comment by d-shaun** [comment]
Your setup looks beautiful.
Also this lmao 
```
$ tuxi --help
/usr/bin/tuxi: illegal option -- -
```
![image](https://user-images.githubusercontent.com/59339807/108363308-c35a4800-71c2-11eb-8a6e-4c1cbcb882d6.png)

**Comment by owl4ce** [comment]
> Your setup looks beautiful.
> Also this lmao
> 
> ```
> $ tuxi --help
> /usr/bin/tuxi: illegal option -- -
> ```
> 
> ![image](https://user-images.githubusercontent.com/59339807/108363308-c35a4800-71c2-11eb-8a6e-4c1cbcb882d6.png)

dude, that's a part of test

**Comment by Bugswriter** [comment]
I added general gif. I want to make .. read me like this .. feel free to do more tweaks ..to improve the read me look.
Also I don't know Where Should I put scripting gif?

**Comment by colonvirus** [comment]
@Bugswriter, can you speed up the gif?

Put the scripting gif after Usage's help text?

**Comment by owl4ce** [comment]
It actually gets converted to fps 10 after ffmpeg from mp4 to gif

origin:
https://user-images.githubusercontent.com/53987136/108368241-ca1da500-722c-11eb-99c4-adda7013b11e.mp4

scripting.gif doesn't really matter, I just made it clear what raw (-r) means

**Comment by colonvirus** [comment]
> Video can't be played because the file is corrupt.

**Comment by owl4ce** [comment]
I wonder why (._.)

**Comment by owl4ce** [comment]
> > Video can't be played because the file is corrupt.

echo "aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2RyaXZlL2ZvbGRlcnMvMVIxNjNjTGo4ZTFCWmFoV0Nr                             
X183WUJUYU1CLUxnUXF0XD91c3BcPXNoYXJpbmcK" | base64 -d

**Comment by Bugswriter** [comment]
> @Bugswriter, can you speed up the gif?
> 
> Put the scripting gif after Usage's help text?

Yeah . .we can do that. But first can someone tell me how to use imagemagick to speed up gif? I am having issue speeding up gif.

**Comment by owl4ce** [comment]
Wait for a moment, I'll convert with higher fps.

**Comment by owl4ce** [comment]
> Wait for a moment, I'll try convert with higher fps using ffmpeg.

Sorry, I failed because I have lowspec pc 😿 

FPS 30 consumes all cpu. Lagging.

**Comment by colonvirus** [comment]
Nah, this is fine.
Let them read.

**Comment by Genghius** [comment]
this has been added, this issue can be closed now.
