### ISSUE TITLE
[Suggestion] Quotation support.

### ISSUE THREAD

**Issue by Bugswriter** [Bugswriter/tuxi#50]
Some people are messaging me asking for quotation support which is possible with this -
`pup 'div[data-mh="-1"] i text{}'"` This will do the trick but also checkout this -

I asked to create this in one of my video and someone made this -
https://github.com/pystardust/quotes 
This script putting '*' in front of quotation which is similar to list view. 
 
![image](https://user-images.githubusercontent.com/23283318/108348567-f5da6400-7207-11eb-8f6e-37cf9f888e63.png)

**Comment by Genghius** [comment]
if quotes have a different tag than knot_top, it can be easy to just surround them with "".
