### ISSUE TITLE
Feature request: Add weather support.

### ISSUE THREAD

**Issue by rushdabs** [Bugswriter/tuxi#53]
I don't know shell script so I can't contribute something myself.
Please add support for weather i.e something like "tuxi nyc weather" will show New York's weather from this [box.](https://www.google.com/search?sxsrf=ALeKk02gG_VUkKsNXMu_vYDZy1CsyhEfOg%3A1613652473803&ei=-WEuYIbFMOrhz7sPi8e5uAQ&q=nyc+weather&oq=nyc+weather&gs_lcp=Cgdnd3Mtd2l6EAMyDAgAELEDEEMQRhCAAjIECAAQQzIICAAQsQMQgwEyBQgAEMkDMgIIADICCAAyAggAMgIIADICCAAyAggAOgcIABBHELADOgcIIxDqAhAnOgQIIxAnOgUIABCRAjoICC4QsQMQgwE6BQgAELEDOgoIABCxAxCDARBDOgUILhCxAzoHCC4QsQMQQzoHCAAQsQMQQzoOCC4QsQMQgwEQxwEQowI6DQgAEIcCELEDEIMBEBQ6CwgAELEDEIMBEMkDOgoIABCxAxCDARAKOggILhDHARCvAVCP_gFYyakCYN-qAmgJcAJ4AIABzQGIAZQQkgEGMC4xNS4xmAEAoAEBqgEHZ3dzLXdperABCsgBCMABAQ&sclient=gws-wiz&ved=0ahUKEwjGpffzu_PuAhXq8HMBHYtjDkcQ4dUDCA0&uact=5)

**Comment by Bugswriter** [comment]
Just update .. this feature has already been added.

**Comment by rushdabs** [comment]
Btw, its not in the AUR yet.

**Comment by d-shaun** [comment]
> Btw, its not in the AUR yet.

The AUR package [tuxi-git](https://aur.archlinux.org/packages/tuxi-git/) builds tuxi from the latest commit of this repo (`main` branch), so it indeed *is* in the AUR.

**Comment by rushdabs** [comment]
Ok ok, is this lag that I'm getting from yay?
