### ISSUE TITLE
Feature list + TODOs

### ISSUE THREAD

**Issue by colonvirus** [Bugswriter/tuxi#55]
## Search
* [x] **Did you mean** (typo checking)
* `tuxi linux torvalds`
* [x] **Math** (calculator)
* `tuxi "log_2(3) * pi^e"`
* [x] **Knowledge Graph - top** (list)
* `tuxi the office cast`
* [x] **Knowledge Graph - right**
* `tuxi the office`
* [x] **Basic Answers**
* `tuxi christmas day`
* [x] **Rich Answers**
* `tuxi elevation of mount everest`
* [x] **Featured Snippets**
* `tuxi who is garfield`
* [x] **Lyrics**
* `tuxi gecgecgec lyrics`
* [x] **Translate**
* `tuxi i love you in spanish`
* [x] **Weather**
* `tuxi weather new york`
* [x] **Units Conversion**
* `tuxi 1m to cm`
* [x] **Currency Conversion**
* `tuxi 1 USD to rupee`
* [x] **Dictionary** _[develop branch]_
* `tuxi define google`
* [x] **Rich Answers** (list type) _[develop branch]_
* `tuxi game of thrones s03 episodes`
* [ ] Calculator - Value of Physical Constants
* `tuxi speed of sound`
* [ ] Geometry Calculator
* `tuxi formula for a triangle perimeter`
* [ ] Diseases (green box on the right)
* `tuxi aids`
* [ ] Quotes
* `tuxi gandhi quotes`
* [ ] ~~_Random_~~
* ~~`tuxi roll a dice`~~

## Others
* [ ] Subtitles of Knowledge Graph - top (list)
* `tuxi tallest buidings` only lists the titles (Burj Khalifa, Shanghai Tower, ...)
* Subtitles are the heights (828m, 632m, ...)
* [ ] Featured Snippets url

Suggestions would be great 😃

**Comment by Bugswriter** [comment]
I was expecting a pull request of this .. instead of issue. LOL. in my gif issue I also mentioned this. 
Should I left this issue open . . Or fix this in that gif issue .. 
Also Only feature will look nice .. These examples are not look good like this.

**Comment by Bugswriter** [comment]
Also add quotations too.

**Comment by colonvirus** [comment]
Where do we keep the TODO then?

**Comment by Bugswriter** [comment]
lets keep this issue open. We will close this when we get todo in readme

**Comment by Genghius** [comment]
tuxi already has functionality to scrap diseases via `knot_rigth`
![image](https://user-images.githubusercontent.com/62076069/108382652-f1f71380-7200-11eb-8754-6589997f2dff.png)
![image](https://user-images.githubusercontent.com/62076069/108382709-00452f80-7201-11eb-8c99-1c2d01c89b9e.png)

**Comment by colonvirus** [comment]
![1613664577](https://user-images.githubusercontent.com/67523247/108385804-09022980-7232-11eb-8d4f-98ad65614694.png)
![1613664610](https://user-images.githubusercontent.com/67523247/108385814-0acbed00-7232-11eb-9fa6-decf768ef820.png)

**Comment by colonvirus** [comment]
Mine is Indian, so it has a different one.

**Comment by owl4ce** [comment]
It seems that this issue needs to be **pinned**.

**Comment by Genghius** [comment]
Are the readmes of `develop` and `main` supposed to not be the same?

**Comment by Genghius** [comment]
If not, I will make a pr to make them both even.

**Comment by owl4ce** [comment]
I think. If tuxi file have changed, the README must also match. It won't be confusing.

**Comment by Genghius** [comment]
ok, imma make the pr.

**Comment by BeyondMagic** [comment]
Random should be removed from the list, see #61.

**Comment by Bugswriter** [comment]
This is a issue .. we get different results in different regions. It's better to just add scraping for all types of responses. and prioritize properly.

**Comment by BeyondMagic** [comment]
This is from google itself..., it gives different results because of the IP location you're using. The only way to avoid that is using proxy/vpn, I think.

But I remember when this was using `gsearch` it did give results from the google account's settings you gave, like location and language.

**Comment by Bugswriter** [comment]
yes but problem is still same. even in gsearch. .. It's better to just add every kind of response. and prioritize.

**Comment by sudocanttype** [comment]
@Bugswriter What if we were to make a public [https://trello.com/](Trello), with us contributors as people with edit access. It would be easier to handle and work better than just continuously commenting on a issue board.

**Comment by Bugswriter** [comment]
yes. Good idea. but trello We can use github projects?

**Comment by sudocanttype** [comment]
Yep, they do the same thing. And I'm pretty sure github projects will be more accessible for other people

**Comment by rezaxd** [comment]
Hey everybody!
I think we can add Table Snippets (example search: what is healthy bmi) and Related Searches that shows in the end of page.
For display tables in terminal I, think we can use awk or jq.
And for Related Searches, we can add switch which using of that make them visible.
I'll create PR for these asap.

**Comment by colonvirus** [comment]
Great, but we're holding off new features for now. The code's too messy. You can PR once it's okay.
