### ISSUE TITLE
Add version?

### ISSUE THREAD

**Issue by colonvirus** [Bugswriter/tuxi#58]
Version 1.0 or something else?

**Comment by owl4ce** [comment]
https://semver.org/

**Comment by Bugswriter** [comment]
Actually I was wondering how about packages? and release ? I think we have to do this .. for taking this project on next leve. may be in future this will get into Arch main repo :)

**Comment by colonvirus** [comment]
We added backward compatible functionalities
so
1.MINOR then

Does `--help` count?  😂

**Comment by colonvirus** [comment]
No, we were in the inital development phase
0.MINOR

This is ready for release so I think this should be 1.0.0

**Comment by Bugswriter** [comment]
I don't know much about versions and stuff. But I truly believe we need this.

**Comment by Genghius** [comment]
#62 includes version option

**Comment by Genghius** [comment]
done, this issue can be closed.
