### ISSUE TITLE
add a license

### ISSUE THREAD

**Issue by monarrk** [Bugswriter/tuxi#6]
please

**Comment by sh4d0wph03n1x** [comment]
His current Lisence is awesome

**Comment by Bugswriter** [comment]
we don't do that here.

**Comment by Bugswriter** [comment]
Also I don't have any knowledge about Lisence .. How can I add any random Lisence without reading and understanding. Sorry. I have to close this issue. I want anyone to use this script Anyway he want.

**Comment by monarrk** [comment]
that's understandable. perhaps you could consider using the unlicense? it's basically that

**Comment by Bugswriter** [comment]
No yesterday A guy convinced me to add a proper License and since I Love GNU. I will add GPL

**Comment by notKamui** [comment]
👍
