### ISSUE TITLE
Define <word> not working properly.

### ISSUE THREAD

**Issue by Bugswriter** [Bugswriter/tuxi#68]
- `shell` zsh
- `Operating system/version`: artix
- `Terminal name/version`: st
- `$TERM` st

## Steps to Reproduce the Problem
`tuxi define humor`

## Expected Behavior
The funny or amusing qualities of somebody/something

## Actual Behavior
No Results!

I believe this https://github.com/Bugswriter/tuxi/pull/64 isn't working properly ..this may be because ..this issue of using tuxi as a dictionary by scraping ..define <word> is not simple. Sometimes google give multiple response. See this -

![image](https://user-images.githubusercontent.com/23283318/108389302-8c714a00-7235-11eb-9505-c92cda7c5287.png)

**Comment by Genghius** [comment]
i will try fix this in my pr, coming in 20 minutes.

**Comment by igaurab** [comment]
![image](https://user-images.githubusercontent.com/28226423/108389554-e2df8800-7237-11eb-9930-5d69f1062386.png)

It's kind of weird. I got the results in mine.

**Comment by Bugswriter** [comment]
may be this is happening because google give different results according to location.

**Comment by Genghius** [comment]
nope, something broke everything else.
-units and currency are not working sometimes
-`tuxi the meaning of life the universe and everything else` is not working.
imma take a while fixing this.

**Comment by igaurab** [comment]
Oops :(

**Comment by Genghius** [comment]
ok, the things were only half-broken, the tuxiqualitytest.sh script was the most broken. someone changed it to use printf and stuff.

**Comment by BeyondMagic** [comment]
You're right, the test is broken, but tuxi itself is not.

**Comment by Genghius** [comment]
yes. 
@Bugswriter from now on i am the absolute authority over the tests for tuxi, XD.

**Comment by Bugswriter** [comment]
I think testing tuxi will take more than just a test script. We need to volunteer some people ask them to try tuxi in order to find bugs by searching weird stuff.
Looking for queries which get answer on google search result but not from tuxi. 
BTW I know about a secret bug since the moment of creating this script. I can't believe no one noticed it .. even after so many users now. Still waiting someone find this bug  XD . Or I will open issue once we get around with all our current issues.

**Comment by igaurab** [comment]
> may be this is happening because google give different results according to location.

This hypothesis might be true, I used VPN to change to three different locations, USA, Europe and Japan. 

The command worked in USA and Europe, but not in Japan. The commands featured in the README.md also didn't work while I was connected to Japan.

**Comment by Genghius** [comment]
> I think testing tuxi will take more than just a test script. We need to volunteer some people on different locations ask them to try tuxi in order to find bugs by searching weird stuff.
> Looking for queries which get answer on google search result but not from tuxi.
> BTW I know about a secret bug since the moment of creating this script. I can't believe no one noticed it .. even after so many users now. Still waiting someone find this bug XD . Or I will open issue once we get around with all our current issues.

certainly, a few set cases wont help us find bugs. but lets atleast force every new PR to pass every test in the script so that we stop having broken versions.

**Comment by Bugswriter** [comment]
When you get no results .. There is HUGE list of possibilities. Which we don't know .. may be it's because google is detecting tuxi as bot .. I think we need something --debug ..which print whole webpage so we can ... redirect it in > tmp.html and open html in firefox to know what we are getting?

**Comment by Bugswriter** [comment]
> > may be this is happening because google give different results according to location.
> 
> This hypothesis might be true, I used VPN to change to three different locations, USA, Europe and Japan.
> 
> The command worked in USA and Europe, but not in Japan. The commands featured in the README.md also didn't work while I was connected to Japan.
> 
> ![image](https://user-images.githubusercontent.com/28226423/108393075-677fd580-723b-11eb-8f7c-66dfb0884110.png)

I believe you are not getting any response from google. Also no need to mention --debug in the Usage ..this will be just hidden in codes ..for us to check what we are getting?

**Comment by igaurab** [comment]
Yup you are correct, I am getting `302 Moved` as response.

**Comment by Genghius** [comment]
this issue can be closed now.
