### ISSUE TITLE
[Suggestion] Add location in Issue template

### ISSUE THREAD

**Issue by Bugswriter** [Bugswriter/tuxi#69]
I guess we need to know about the location of the google search. 
We are getting different answers. with same code. 
This is not easy to tackle because we will never know what kind of results google provide in different-2 locations.

**Comment by Bugswriter** [comment]
I think we need a strong testing mech. before adding new feature. We need to run tests on variety of locations.

**Comment by Genghius** [comment]
tuxiqualitytest.sh did that, but someone changed it and now it doesnt work properly, imma rollitback for my pr.
