### ISSUE TITLE
Just getting "wait what?"

### ISSUE THREAD

**Issue by hum4nizer** [Bugswriter/tuxi#7]
Hello and thanks for a cool script. But the only return I get is "Wait what?". What can be wrong? Probably something with the curl URL?

**Comment by Bugswriter** [comment]
I think this is because of my new merge of pull request .. Well that's not good. Let me look into this. Just wait for a bit.

**Comment by Bugswriter** [comment]
Ok so I tested tuxi .. it's working fine. I think it's only on your computer. 
Try this : 
Open tuxi script after that curl command when you have webpage variable just echo $webpage and exit 
This way you will get whole webpage then
tuxi linux > tmp.html
firefox tmp.html
and tell me what you see?

**Comment by hum4nizer** [comment]
Hey!

Thanks for your reply. I see the following:
![image](https://user-images.githubusercontent.com/52622131/108068874-f4236b80-7062-11eb-8400-b508ec67c86f.png)

**Comment by hum4nizer** [comment]
I found the error. I gsearch the curl line started with curl -s 'https://www.google.com/search?q=$1' -H 'User-Agent: Mozilla/5.0 
But off course the correct line should start with: 'https://www.google.com/search?q='$1 -H 'User-Agent: Mozilla/5.0 

Thanks!
