### ISSUE TITLE
Add url for source of answer

### ISSUE THREAD

**Issue by lodenrogue** [Bugswriter/tuxi#71]
I'd like an option to see the url where tuxi got it's answer from. Maybe I want more info or want to go to the page and see what else the article is talking about.

**Comment by BeyondMagic** [comment]
Hmmmm

**Comment by Bugswriter** [comment]
This can be done when we get knowledge graph on top. We have to write a if statement ..to grab URL before printing the answer and terminating the script. 
But .. I think this will complicate things
I guess Siri also say "according to <website>

**Comment by BeyondMagic** [comment]
This would means using `pup` twice (more one class to maintain), one to get the link and other to get the answer, not every scrapping gives a link, too, only a few.

**Comment by Genghius** [comment]
> I'd like an option to see the url where tuxi got it's answer from. Maybe I want more info or want to go to the page and see what else the article is talking about.

we are scrapping google's featured answers, if you google the same question you ask tuxi, it will show the same answers. is this what you meant or want the url for script purposes?

**Comment by lodenrogue** [comment]
I would like the url of the source not google. So for example if I search for 
```
tuxi who is sundar pichai
```
I would like an option to get the url. Maybe wikipedia is the source.

**Comment by Genghius** [comment]
> I would like the url of the source not google. So for example if I search for
> 
> ```
> tuxi who is sundar pichai
> ```
> 
> I would like an option to get the url. Maybe wikipedia is the source.

![image](https://user-images.githubusercontent.com/62076069/108397437-de9f7480-720f-11eb-9552-0f89432d6e0e.png)
it seems quite easy, the link is always within the same div, when you manage to add the option, make a pull request.

**Comment by Bugswriter** [comment]
but guys .. I think if by default we unable this .. This is not a good idea. People really don't want all these extra stuff. The thing I like about tuxi is we only GET what we care about. 

I think we should talk about this feature by default or not?

**Comment by lodenrogue** [comment]
Yeah it should not be by default. It should be an --option only

**Comment by PureArtistry** [comment]
coming very soon...
![scrot_20210309-000446](https://user-images.githubusercontent.com/53883649/110398300-7eac2900-806b-11eb-9e8c-3d2878776506.png)

**Comment by lodenrogue** [comment]
Looks great!

**Comment by Niarch** [comment]
Looks clean....we could add this to a .tuxirc file or something to enable URL or not
