### ISSUE TITLE
--debug option which return html of page

### ISSUE THREAD

**Issue by Bugswriter** [Bugswriter/tuxi#74]
Ok, I think So need to hide this --debug option in our code .. so We can do

`tuxi --debug define gambling > tmp.html`

This way we can look at the page we are getting .. in browser to know what is happening?

**Comment by colonvirus** [comment]
Yep that's cool
But getops doesnt support flags, so -d will do

**Comment by Bugswriter** [comment]
--debug would be cool but . that's not an issue.

**Comment by colonvirus** [comment]
where should the logs go?

**Comment by Genghius** [comment]
This Issue can be closed now.

**Comment by Genghius** [comment]
@Bugswriter ^^^

**Comment by Bugswriter** [comment]
No .. its not working correctly .. The html debug option generate is not actually html .. its utf 8 text. Browser open the text.

**Comment by colonvirus** [comment]
Firefox opened the html for me

**Comment by Bugswriter** [comment]
strange I also used firefox. I ll test again  soon. lets keep this issue open

**Comment by BikramKumar6928** [comment]
@Bugswriter maybe use this answer to add --debug flag.
This allows you to add long flags while getting options.
Just a suggestion. 

https://stackoverflow.com/a/7069755

**Comment by Bugswriter** [comment]
no need since we are not going to show --debug in your -h help. and It's just for devs. I guess Why bother. We will use `-d`
