### ISSUE TITLE
Package everything into one installation

### ISSUE THREAD

**Issue by ShivamJoker** [Bugswriter/tuxi#75]
It's very difficult to get all the other dependencies and make this thing work, it'll be helpful if someone can add other tools installation in some script

**Comment by Genghius** [comment]
we already went over this with the docker guys, its only 3 deps, 2 of them you clone directly from github, the other only needs you to have go.

Also, there is an aur package for this, so you can alternatively use that.

it shouldnt be difficult to install the deps in theory...

**Comment by Bugswriter** [comment]
I wish pup will get into Arch official repo. This will make things easy.

**Comment by SomethingGeneric** [comment]
Debian package also perhaps?

**Comment by SomethingGeneric** [comment]
> It's very difficult to get all the other dependencies and make this thing work, it'll be helpful if someone can add other tools installation in some script
Getting Pup on Ubuntu to test was a pain but that's more of a Pup issue. Not sure which dep was giving you trouble tho

**Comment by Ashdemai** [comment]
Yeah, I can't install the dependencies. I guess I'm out of luck.

**Comment by h4de5** [comment]
@Ashdemai https://github.com/Bugswriter/tuxi/issues/34#issuecomment-782773306
