### ISSUE TITLE
Test was merged to main?

### ISSUE THREAD

**Issue by officialcactar** [Bugswriter/tuxi#78]
The testing script should probably be removed from main branch.

**Comment by Genghius** [comment]
yes.

**Comment by Bugswriter** [comment]
You mean old test ..in main?

**Comment by officialcactar** [comment]
> 
> 
> You mean old test ..in main?

tuxiqualitytest.sh

**Comment by Bugswriter** [comment]
Guys what is testoutputs.txt ? Do I need it to test the script if yes then.. are you comparing the prestored answers
if yes then .. Answers can vary?

**Comment by Genghius** [comment]
> Guys what is testoutputs.txt ? Do I need it to test the script if yes then.. are you comparing the prestored answers
> if yes then .. Answers can vary. This is not a good way.

testoutputs.txt is just a file that stores the output of the commands run tuxiqualitytest.sh
it will be created automatically every time you run the test script, i would recomend deleting it before doing git push so that it doesnt come here with garbage output.

**Comment by Genghius** [comment]
> Guys what is testoutputs.txt ? Do I need it to test the script if yes then.. are you comparing the prestored answers
> if yes then .. Answers can vary. This is not a good way.

and no comparison is being made with the answers, they are just being stored so that the user can cat the file and make sure all output is formated correctly.

**Comment by Bugswriter** [comment]
> > Guys what is testoutputs.txt ? Do I need it to test the script if yes then.. are you comparing the prestored answers
> > if yes then .. Answers can vary. This is not a good way.
> 
> and no comparison is being made with the answers, they are just being stored so that the user can cat the file and make sure all output is formated correctly.

Oh got it.

**Comment by Bugswriter** [comment]
Should I close this issue..now?
