### ISSUE TITLE
[[: not found

### ISSUE THREAD

**Issue by shougyin** [Bugswriter/tuxi#8]
Not sure why I keep getting this at the start, any ideas?

![image](https://user-images.githubusercontent.com/34975201/107991880-89602a80-6fa5-11eb-8cc2-bbcb39835eae.png)

**Comment by Bugswriter** [comment]
which shell you are using?

**Comment by shougyin** [comment]
zsh

**Comment by Bugswriter** [comment]
that's strange. I am also using zsh .. I also tested this on bash. .. I don't get this issue. 
wait let me see.

**Comment by Bugswriter** [comment]
Try to replace [[ with [ and ]] with ] .. Sorry but try to do this .. This might fix your issue do it for one line and see. if you are getting error for that particular line?

**Comment by shougyin** [comment]
Awesome, that fixed all of them.  Thanks!  Works great!

**Comment by Bugswriter** [comment]
are you getting one word answer when you try to ask one word question?
Like Linus torvalds birthday?
Becase in your SS you are getting a paragraph where I am getting simple answer Mount Everest.

**Comment by wahlis** [comment]
I get a similar issue, but also it seems to use a localized version of Google which defaults to Swedish.
![Skärmbild 2021-02-15 223609](https://user-images.githubusercontent.com/1257241/107995058-dcea6c80-6fd5-11eb-925e-3d047c2f6c76.jpg)

**Comment by shougyin** [comment]
It is now giving me Mount Everest as the answer
