### ISSUE TITLE
Raw output not sanitizing errors

### ISSUE THREAD

**Issue by SomethingGeneric** [Bugswriter/tuxi#83]
## Leaving this open anyway to see if there's a change that can allow flags on either side

- `zsh`
- `Arch Linux`:
- `GNOME Terminal`:
- `echo $TERM` = `xterm-256color`

## Steps to Reproduce the Problem

* `tuxi -r "Barack Obama"` -> `No Result!` (in red)
* `tuxi -rq "Barack Obama"` -> `No Result!` (in red)

## Expected Behavior

`No Result!` in plaintext

## Actual Behavior

![Screenshot from 2021-02-18 13-32-33](https://user-images.githubusercontent.com/12242178/108404433-d7676f00-71ed-11eb-8f33-be54d5bd6d37.png)

**Comment by Genghius** [comment]
i dont remember who wrote the text formatting, but lets just wait for him to read this and fix it xd.

**Comment by colonvirus** [comment]
You have search
`tuxi -r <query>`
not
`tuxi <query> -r`

It's a limitation of getopts
For now

**Comment by SomethingGeneric** [comment]
@colonvirus you're totally right. My bad for not checking that. Might leave this open to remind myself to see if there's any workaround to that

**Comment by Bugswriter** [comment]
> You have search
> `tuxi -r <query>`
> not
> `tuxi <query> -r`
> 
> Tuxi treats **-r** as a part of the query if its after the query

You are right but why he is getting No result for barak obama?

**Comment by SomethingGeneric** [comment]
> You are right but why he is getting No result for barak obama?

That seemed like a fluke It spit out a result when I used `tux -rq "Barack Obama`
![Screenshot from 2021-02-18 13-43-13](https://user-images.githubusercontent.com/12242178/108405620-472a2980-71ef-11eb-95fe-8d067ec2ec6d.png)

**Comment by colonvirus** [comment]
> You are right but why he is getting No result for barak obama?

Cuz tuxi treats the query as "Barack Obama -r"
Which doesn't give the above result in google

**Comment by colonvirus** [comment]
Fixing this would mean removing all arguments after the query, that have a hyphen in it
Seems doable but messy

**Comment by colonvirus** [comment]
Sanitizing options with arrays would be cleaner, but since arrays aren't posix, it would be messy

**Comment by Bugswriter** [comment]
> > You are right but why he is getting No result for barak obama?
> 
> Cuz tuxi treats the query as "Barack Obama -r",
> which doesn't give the above result in google

But we are using quotation. :( 
That's not good

**Comment by colonvirus** [comment]
`query="$*"`
this gobbles up everything after the options

**Comment by Bugswriter** [comment]
oh yes. This is one of my code. LOL. you guys really changed the script so much. 
This is not a big issue .. if user use things incorrectly .. he deserve to get punished with No result.
