### ISSUE TITLE
Priority discussion

### ISSUE THREAD

**Issue by colonvirus** [Bugswriter/tuxi#84]
```
# Did you mean
# Math
# Knowledge Graph - top
# Dictionary
# Basic Answers
# Rich Answers
# Rich List
# Featured Snippets
# Lyrics
# Weather
# Units Convertion
# Currency Convertion
# Knowledge Graph - right
# Translate
```

We can prioritize based on relevance and speed.
Math should be at the top, and Knowledge Graph - right 
should be near the bottom as it's like a catch-all.

We could add the first google link instead of no results, like Siri.

Suggestions please 🙏

EDIT: Translate at the bottom, and Knowledge graph - right, right before it

**Comment by d-shaun** [comment]
Hmm, afaik from a few minutes earlier, having rich list before weather and translate breaks both of them.

**Comment by Genghius** [comment]
Translate should be the last one, it is the slowest of them all.

**Comment by Genghius** [comment]
the order i put in `panacea 3` was good enough.

**Comment by colonvirus** [comment]
> Hmm, afaik from a few minutes earlier, having rich list before weather and translate breaks both of them.

Can you fix that?
Translate is slow, so getting a rich list would be slow too.

**Comment by Bugswriter** [comment]
I think knowledge graph should not be on top?

**Comment by Bugswriter** [comment]
> Translate should be the last one, it is the slowest of them all.

How you can say? Also why. we are scraping every scrape should be in similar time. Except list Ig.

**Comment by Bugswriter** [comment]
I think we need to create a file or something where we also put the Image with all these options. This way it will be easier to understand what things we are scraping though google search. I know it's pain to do this but. . This will give a really good picture. Trust me.

**Comment by colonvirus** [comment]
Yea, I thought about it too.
I'll do that tomorrow.

**Comment by Bugswriter** [comment]
> Yea, I thought about it too.
> I'll do that tomorrow.

yeah you are from India ..ig we both should sleep.. tomorrow we will create a file.

**Comment by Genghius** [comment]
i have an idea
Make every scrap a function, call every function with &. Done Magick, speed doesnt matter anymore.

**Comment by Bugswriter** [comment]
Hmm. the way this project is growing. IG we should, Then we can just add functions to add functionality. I think it's better than this linear way. BTW more feature we add .. more slower will script get for features which are not on top.
