### ISSUE TITLE
[Suggestion] Option for --all ?

### ISSUE THREAD

**Issue by Bugswriter** [Bugswriter/tuxi#86]
Dump every information we get instead of just with priority order?
But after filtering out blank variables? 
 
![image](https://user-images.githubusercontent.com/23283318/108417569-25b05880-7256-11eb-9d54-0dc3493f28b7.png)

```
$ tuxi -a cristmas day
25, December 2021
Christmas is an annual festival commemorating the birth of Jesus Christ, observed primarily on
December 25 as a religious and cultural celebration by billions of people around the world. 
```
This will help when we get some information on top knowledge graph also on right.
Terminating after prioritizing restricting user to get information which he can get. 
If user want to get all information our script is capable of scraping but will not scrape? and user can't do anything about this.

**Comment by Bugswriter** [comment]
@BeyondMagic Dude you forget to add -a option in help_text

I see no option of -a ?

**Comment by Genghius** [comment]
imma make this part of my PR today

**Comment by Genghius** [comment]
it was already added. this pr can be closed.
