### ISSUE TITLE
[installation process] it should be sudo make

### ISSUE THREAD

**Issue by Bugswriter** [Bugswriter/tuxi#88]
We have makefile Idk why instead of `sudo make` we have curl way to install?
We are so pros we forget .. that many ubuntu newbies are unable to install ..because not everyone have ~/.local/bin
even if they create .. they don't have env path variable set for it.

**Comment by sudocanttype** [comment]
For the complete ubuntu noobs, we could create a installation sh file that does all of that. That being said, it would be a super small bash script.

**Comment by Bugswriter** [comment]
but why .. we have makefile?

**Comment by Bugswriter** [comment]
Somebody just change readme and put make method of installation @Genghius ? can you. I am not good with tweaking read me writing instructions.

**Comment by owl4ce** [comment]
/usr/local/bin

**Comment by Bugswriter** [comment]
Yeah and that solution is already implemented in `make`?
Just change the Installation instruction and .. that's it.

**Comment by owl4ce** [comment]
can it be like this?
```sh
$ sudo curl -sL "https://raw.githubusercontent.com/Bugswriter/tuxi/main/tuxi" -o /usr/local/bin/tuxi
$ sudo chmod +x /usr/local/bin/tuxi
```

Or do create a script for automatic installation, where the user only needs to curl the installation script.
![image](https://user-images.githubusercontent.com/53987136/108466216-ddc11e00-72b5-11eb-8481-2c4efb60b7cc.png)

**Comment by Bugswriter** [comment]
umm but what is issue with make? why we have makefile then?

**Comment by Bugswriter** [comment]
I guess make is better solution for this? 
just `sudo make`?

**Comment by owl4ce** [comment]
> I guess make is better solution for this?
> just `sudo make`?

Okay, wait for me to update the makefile and readme. 
https://github.com/Bugswriter/tuxi/pull/96

**Comment by gordo1337** [comment]
Been doing the install on mac big sur, i had  to add #!/bin bash in ~/.local/bin/tuxi.
Then run it the script and i get the tuxi [options] query.
But it wont work after that. 
let me se if it will work correct if build it with sudo make instead to.

**Comment by owl4ce** [comment]
> Been doing the install on mac big sur, i had to add #!/bin bash in ~/.local/bin/tuxi.
> Then run it the script and i get the tuxi [options] query.
> But it wont work after that.
> let me se if it will work correct if build it with sudo make instead to.

I think it's just shebang problems about shell PATH

**Comment by Bugswriter** [comment]
> Been doing the install on mac big sur, i had to add #!/bin bash in ~/.local/bin/tuxi.
> Then run it the script and i get the tuxi [options] query.
> But it wont work after that.
> let me se if it will work correct if build it with sudo make instead to.

try new version. We have in our main. 
with 
`sudo make`

**Comment by Bugswriter** [comment]
> > Been doing the install on mac big sur, i had to add #!/bin bash in ~/.local/bin/tuxi.
> > Then run it the script and i get the tuxi [options] query.
> > But it wont work after that.
> > let me se if it will work correct if build it with sudo make instead to.
> 
> I think it's just shebang problems about shell PATH

Is that a big issue?

**Comment by owl4ce** [comment]
> > > Been doing the install on mac big sur, i had to add #!/bin bash in ~/.local/bin/tuxi.
> > > Then run it the script and i get the tuxi [options] query.
> > > But it wont work after that.
> > > let me se if it will work correct if build it with sudo make instead to.
> > 
> > 
> > I think it's just shebang problems about shell PATH
> 
> Is that a big issue?

yes and no

**Comment by Bugswriter** [comment]
I will close this issue once we get sure about. . tuxi have smooth installation process for every Linux distro.

**Comment by owl4ce** [comment]
> Been doing the install on mac big sur, i had to add #!/bin bash in ~/.local/bin/tuxi.
> Then run it the script and i get the tuxi [options] query.
> But it wont work after that.
> let me se if it will work correct if build it with sudo make instead to.

Do you have `/usr/ bin/env` on your Mac?

**Comment by Bugswriter** [comment]
IG we are not going to get this issue in GNU/Linux and Unix based systems ? right. Well that's good.

**Comment by owl4ce** [comment]
Maybe changing shebang to `#!/bin/sh` is fairly common.

**Comment by gordo1337** [comment]
> > > > Been doing the install on mac big sur, i had to add #!/bin bash in ~/.local/bin/tuxi.
> > > > Then run it the script and i get the tuxi [options] query.
> > > > But it wont work after that.
> > > > let me se if it will work correct if build it with sudo make instead to.
> > > 
> > > 
> > > I think it's just shebang problems about shell PATH
> > 
> > 
> > Is that a big issue?
> 
> yes and no

> no, not that big of an issue, i will solve it in some way. just woke up and will probably need som caffine to boost the thinking.

**Comment by gordo1337** [comment]
> > Been doing the install on mac big sur, i had to add #!/bin bash in ~/.local/bin/tuxi.
> > Then run it the script and i get the tuxi [options] query.
> > But it wont work after that.
> > let me se if it will work correct if build it with sudo make instead to.
> 
> Do you have `/usr/ bin/env` on your Mac?

> Yes i do hav usr/bin, will put it there instead. :)  thanks

**Comment by owl4ce** [comment]
> > > Been doing the install on mac big sur, i had to add #!/bin bash in ~/.local/bin/tuxi.
> > > Then run it the script and i get the tuxi [options] query.
> > > But it wont work after that.
> > > let me se if it will work correct if build it with sudo make instead to.
> > 
> > 
> > Do you have `/usr/ bin/env` on your Mac?
> 
> > Yes i do hav usr/bin, will put it there instead. :)  thanks

No, I mean `/usr/bin/env`

**Comment by gordo1337** [comment]
> > > > Been doing the install on mac big sur, i had to add #!/bin bash in ~/.local/bin/tuxi.
> > > > Then run it the script and i get the tuxi [options] query.
> > > > But it wont work after that.
> > > > let me se if it will work correct if build it with sudo make instead to.
> > > 
> > > 
> > > Do you have `/usr/ bin/env` on your Mac?
> > 
> > 
> > > Yes i do hav usr/bin, will put it there instead. :)  thanks
> 
> No, I mean do you have `/usr/bin/env` executable?

> Yes, but tuxi aint there, probably it could also be Zsh that makes the problem to.

**Comment by gordo1337** [comment]
> IG we are not going to get this issue in GNU/Linux and Unix based systems ? right. Well that's good.

> Will do a install on my other workstations in a hour or so. (Deb and Pop os) and hopefully no problems :)

**Comment by owl4ce** [comment]
> > > > > Been doing the install on mac big sur, i had to add #!/bin bash in ~/.local/bin/tuxi.
> > > > > Then run it the script and i get the tuxi [options] query.
> > > > > But it wont work after that.
> > > > > let me se if it will work correct if build it with sudo make instead to.
> > > > 
> > > > 
> > > > Do you have `/usr/ bin/env` on your Mac?
> > > 
> > > 
> > > > Yes i do hav usr/bin, will put it there instead. :)  thanks
> > 
> > 
> > No, I mean do you have `/usr/bin/env` executable?
> 
> > Yes, but tuxi aint there, probably it could also be Zsh that makes the problem to.

It is not like that. If we execute command from `env`, it will use **PATH** environment variables to look for `sh`.

![image](https://user-images.githubusercontent.com/53987136/108471387-e3226680-72bd-11eb-9ff0-cc9878cbac9b.png)

**Comment by owl4ce** [comment]
> ill do a install on my other workstations in a hour or so. (Deb and Pop os) and hopefully no problems :)

Most GNU/Linux doesn't have a problem as having an `env` in `/usr/bin/`.

**Comment by gordo1337** [comment]
Everything worked perfect with the Sudo make command. :) 
Good work! 
(MacOS Big sur )

**Comment by owl4ce** [comment]
Yes it is possible, because before I define the location of the install to `$HOME/.local/bin`. Recently I moved to `/usr/local` for curl and make installation.

**Comment by owl4ce** [comment]
I think this issue needs to be closed?
