### ISSUE TITLE
[Bug] Happened because of #81 Pull

### ISSUE THREAD

**Issue by Bugswriter** [Bugswriter/tuxi#91]
@d-shaun You made a silly mistake with https://github.com/Bugswriter/tuxi/pull/81.
See this list view - 
![image](https://user-images.githubusercontent.com/23283318/108422912-30bab700-725d-11eb-9e8d-cf6b577aee5a.png)

It's "Jessie Eisenberg" This should be in same line and "Andrew Garfield".
LOL .. you should have check properly. 

**But that's not it.**

Now lets just assume your PR doesn't exist. Just revert back to old version in your head, like we have in our main right now. 
That list view with `*` I implemented in my first commit .. was not completely right too.
I knew about this. Sorry didn't open the issue. I was just waiting for someone else to figure out. 
and wow someone did found this. 

So issue was this - https://github.com/Bugswriter/tuxi/issues/89
I close the issue since we already did changes in list functionality with https://github.com/Bugswriter/tuxi/pull/81

But sorry @d-shaun https://github.com/Bugswriter/tuxi/pull/81 seems even worse than the previous list view.

So now the real issue is -
We are in between two versions of lists one is completely openly buggy another is not so easy to find.
Now the solution of this is not easy 
so first we have to revert this https://github.com/Bugswriter/tuxi/pull/81

Then try our best to fix this - https://github.com/Bugswriter/tuxi/issues/89
The reason we are getting https://github.com/Bugswriter/tuxi/issues/89 is because .. I replaces null with next line
I was getting null since we had secondary text 
(go read my comment on https://github.com/Bugswriter/tuxi/issues/89 Explaining what is secondary text)
But if someone do search like - `tuxi list of linux distros` we won't get any secondary text means no null and no next line replacement.

So **"how we are going to fetch list in that case"** is the real issue?

**Comment by BeyondMagic** [comment]
damn!!!

I'll those in #90

**Comment by Bugswriter** [comment]
BTW Right now this repo is on 3rd of [github trending](https://github.com/trending)
![image](https://user-images.githubusercontent.com/23283318/108434225-4df78180-726d-11eb-9f43-da579e4d608c.png)

So please fix this. It's really annoying.

**Comment by sudocanttype** [comment]
![image](https://user-images.githubusercontent.com/61509416/108434455-4bfdd600-720d-11eb-85bc-d82cbe46c324.png)

`kno_top=$(echo "$google_html" | pup 'div.dAassd json{}'  | jq -r '.[] | .children | .[] | .text' | sed ':a;N;$!ba;s/\n/ /g' | sed 's/null/\n/g' | awk '{$1=$1;print "* " $0}' | sed '/^* $/d'| recode html..ISO-8859-1)
[ -n "$kno_top" ] && output "$kno_top" && exit 0
`
This seems to work

**Comment by BeyondMagic** [comment]
> kno_top=$(echo "$google_html" | pup 'div.dAassd json{}' | jq -r '.[] | .children | .[] | .text' | sed ':a;N;$!ba;s/\n/ /g' | sed 's/null/\n/g' | awk '{$1=$1;print "* " $0}' | sed '/^* $/d'| recode html..ISO-8859-1) [ -n "$kno_top" ] && output "$kno_top" && exit 0 

We need the secondary text yet. I think jq can do most of the work without sed, I'l try to simplify it, thanks.

**Comment by Bugswriter** [comment]
You are not getting. We can use null ..  we need to create another method of fetching lists in a way, so we can fix 
https://github.com/Bugswriter/tuxi/issues/89

**Comment by Bugswriter** [comment]
> > kno_top=$(echo "$google_html" | pup 'div.dAassd json{}' | jq -r '.[] | .children | .[] | .text' | sed ':a;N;$!ba;s/\n/ /g' | sed 's/null/\n/g' | awk '{$1=$1;print "* " $0}' | sed '/^* $/d'| recode html..ISO-8859-1) [ -n "$kno_top" ] && output "$kno_top" && exit 0
> 
> We need the secondary text yet. I think jq can do most of the work without sed, I'l try to simplify it, thanks.

Yes I was not very good with jq. But I tried and failed.
We need a ways so we get list output like this -

_When we do type one search (with secondary text)_
* item (secondary text)

_When we do type two search (no secondary text)_
* item

**Comment by Bugswriter** [comment]
I have one idea. We first test whether we have any secondary text in our list .. or not 
than simple if else and
we can create two methods of scraping lists one for with sec text one without sec text.
but I think we should first make functions for that. @Genghius suggested that. I think this will make things clean.

**Comment by BeyondMagic** [comment]
I found the solution, we were scrapping the wrong things all the way along.

![image](https://user-images.githubusercontent.com/51831435/108436565-63978780-722a-11eb-9520-8939e3dee2fc.png)

**Comment by Bugswriter** [comment]
What do you mean by wrong thing? Also is your solution is working for .. Linux distro and NFS condition too?

**Comment by BeyondMagic** [comment]
I mean, the wrong elements.

It's working for bash/sh obviously, but I have to see if there's bashism in the #90 to work on MacOS and everything else...

NFS condition is not working yet, but I can fix it.

**Comment by Bugswriter** [comment]
That's the whole point .. getting both working correctly.
I don't think it's possible with one single scraping. But keep trying. Lets see ..
Also I am going to sleep. Please try fixing this and when other dev wake up .. take help.

**Comment by BeyondMagic** [comment]
Both are working now.

![image](https://user-images.githubusercontent.com/51831435/108437417-0ef50c00-722c-11eb-8f3a-0f182dfca06d.png)

**Comment by Bugswriter** [comment]
wow beautiful ..but why not `*` for type 2 list search?

**Comment by BeyondMagic** [comment]
I'll add it right now, do I remove the "View all" in the last item?

**Comment by Bugswriter** [comment]
Test this properly and give me a PR I want to see the code.

**Comment by BeyondMagic** [comment]
I'll push soon to #90 .

**Comment by Bugswriter** [comment]
> I'll add it right now, do I remove the "View all" in the last item (second list)?

ofc.

**Comment by Bugswriter** [comment]
> I'll push soon to #90 .

I am holding my sleep. eagerly waiting.

**Comment by BeyondMagic** [comment]
Good night, bro.
