### ISSUE TITLE
[Bug] not getting proper translation.

### ISSUE THREAD

**Issue by Bugswriter** [Bugswriter/tuxi#93]
Sorry for not following the Issue template.

Here I am getting this (second one is correct .. first one is wrong) -

![image](https://user-images.githubusercontent.com/23283318/108438786-fc9fc000-7275-11eb-9f95-73911607a38f.png)

But we have result in google search -
![image](https://user-images.githubusercontent.com/23283318/108438830-104b2680-7276-11eb-8042-58dd9525e8cf.png)

We have to make tuxi less peculiar 
Look if you are not using any solid class or id name in pup.

Suggestion - try to use .. ID Look for parent blocks ..because ID is only one.

**Comment by BeyondMagic** [comment]
Is this the develop branch?

**Comment by Bugswriter** [comment]
Yes only in develop branch in main branch I am getting answer of power and fuck but. . those answers are not meaning of word. Tuxi is using knowledge graph of right side.

**Comment by BeyondMagic** [comment]
This is my fault, try using the option `-a` to get all the results. It seems that something is parsing before, you can fix it, I'll pass the code for you soon.

**Comment by Bugswriter** [comment]
i am getting no output with `-a` also there is no mention of `-a` in tuxi -h 
one more issue is .. the html we get from `-d` debug . it's text .. when I open it in browser instead of html page I am getting all code??
I ran file command got this - /home/bw/.cache/tuxi/tuxi-1613694919-define_fuck.html: HTML document, UTF-8 Unicode text, with very long lines

**Comment by Bugswriter** [comment]
Really tired going to sleep .. I guess we need a lot to work to make develop branch ready for merging with main. I stopped PR featuring new ..features. We will add those when we get finished with all our current mess.

**Comment by BeyondMagic** [comment]
I'll fix it.

**Comment by Bugswriter** [comment]
Should we close this issue now?

**Comment by colonvirus** [comment]
> i am getting no output with `-a` also there is no mention of `-a` in tuxi -h
> one more issue is .. the html we get from `-d` debug . it's text .. when I open it in browser instead of html page I am getting all code??
> I ran file command got this - /home/bw/.cache/tuxi/tuxi-1613694919-define_fuck.html: HTML document, UTF-8 Unicode text, with very long lines

Oh, I forgot to add quotes around `$google_html`
