### ISSUE TITLE
[Bug] Time now is not working now?

### ISSUE THREAD

**Issue by Bugswriter** [Bugswriter/tuxi#97]
![image](https://user-images.githubusercontent.com/23283318/108470249-af404480-72af-11eb-9ac5-735fa341f9d8.png)

Can someone figure out why we are losing some pre existing functionality?

**Comment by Bugswriter** [comment]
I think our develop branch is having lot of issues in comparison to our main branch. I just tested our current version support `time now` feature
. I think we should make a long test .. with more questions.

**Comment by colonvirus** [comment]
```
# Rich Answers ( eg: elevation of mount everest )
rich=$(echo "$google_html" | pup 'div.XcVN5d text{}' | recode html..ISO-8859-1)
[ -n "$rich" ] && output "$rich" && exit 0
```

This was changed to

```
rich=$(echo "$google_html" | pup 'div.bbVIQb, div.ujudUb, div.mR2gOd text{}' | sed 's/^ //' | recd)
snipcall "$rich"
```

**Comment by colonvirus** [comment]
We need to stop adding any more features till we sort everything out, and make better tests.
+ images for each SERP

**Comment by sudocanttype** [comment]
We should make a more in-depth test script. That being said, we could definitely just program a function that checks for time.

**Comment by Bugswriter** [comment]
Yes I am putting new features on hold.
Also why not just reverting back ? Why we are having this issue?

**Comment by colonvirus** [comment]
```
# This serves for a lot of things, simplified for performance
# Rich Answers      ( eg: elevation of mount everest )
# bbVIQb & ujudUb   ( eg: gecgecgec lyrics )                 ( Lyrics )
# mR2g0d            ( eg: game of thrones s03 episodes )     ( Somewhat complicated lists )
rich=$(echo "$google_html" | pup 'div.bbVIQb, div.ujudUb, div.mR2gOd text{}' | sed 's/^ //' | recd)
snipcall "$rich"
```
this implementation of rich answers doesn't support `time now`

**Comment by Bugswriter** [comment]
> We should make a more in-depth test script. That being said, we could definitely just program a function that checks for time.

No we need to scrape time. I believe time is a rich answer. Also script goal is to just scrape cream information google give except search results.

**Comment by Bugswriter** [comment]
> ```
> # This serves for a lot of things, simplified for performance
> # Rich Answers      ( eg: elevation of mount everest )
> # bbVIQb & ujudUb   ( eg: gecgecgec lyrics )                 ( Lyrics )
> # mR2g0d            ( eg: game of thrones s03 episodes )     ( Somewhat complicated lists )
> rich=$(echo "$google_html" | pup 'div.bbVIQb, div.ujudUb, div.mR2gOd text{}' | sed 's/^ //' | recd)
> snipcall "$rich"
> ```
> 
> this implementation of rich answers doesn't support `time now`

Rich answer is a very important .. Can't we just find one key stuff which is common is all rich answer? or put multiple scrapes for diff-2 conditions?

**Comment by sudocanttype** [comment]
Huh, it looks like time isnt included in tuxi. 
![image](https://user-images.githubusercontent.com/61509416/108471467-0cf17400-7251-11eb-9db7-9eb7ed6b889d.png)
None of these div.classes are referred to in the script

**Comment by colonvirus** [comment]
```
rich=$(echo "$google_html" | pup 'div.XcVN5d text{}' | recode html..ISO-8859-1)
[ -n "$rich" ] && output "$rich" && exit 0

```
This does, but was removed

**Comment by sudocanttype** [comment]
ok then, just add it back. 
![image](https://user-images.githubusercontent.com/61509416/108471697-60fc5880-7251-11eb-851a-88c44a92576a.png)
boom it works

**Comment by Bugswriter** [comment]
> Huh, it looks like time isnt included in tuxi.
> ![image](https://user-images.githubusercontent.com/61509416/108471467-0cf17400-7251-11eb-9db7-9eb7ed6b889d.png)
> None of these div.classes are referred to in the script

Well I guess .XcVN5d is common in every scrape.

**Comment by Bugswriter** [comment]
> ok then, just add it back.
> ![image](https://user-images.githubusercontent.com/61509416/108471697-60fc5880-7251-11eb-851a-88c44a92576a.png)
> boom it works

This looks fine. I guess we will able to get all .. rich text. This is a ++ not -- 
we need to think before tinkering with something which is working.

**Comment by colonvirus** [comment]
Should we document all the div classes?
This will get messy soon

**Comment by sudocanttype** [comment]
Yep, we probably should document all the classes.

**Comment by Bugswriter** [comment]
Yes with images. That's what I am proposing yesterday where should we have a document? I don't think repo is a good idea.

**Comment by colonvirus** [comment]
Wiki?

**Comment by sudocanttype** [comment]
Just ran the quality test script, everything seems to be functioning well after adding the additional div

**Comment by Bugswriter** [comment]
Lol Tuxi wiki .. just make a gist IG

**Comment by Bugswriter** [comment]
We need to extend our qualitytest script to add more. . questions.

**Comment by Bugswriter** [comment]
Guys I am not good with documenting stuff? So who will start .. I ll add stuff. After looking at way you add.

**Comment by colonvirus** [comment]
I'll document it, but I haven't tried gists 😅

**Comment by Bugswriter** [comment]
> I'll document it, but I haven't tried gists sweat_smile

use whatever you like.

**Comment by sudocanttype** [comment]
I can start working on more test cases

**Comment by colonvirus** [comment]
Can I just make a repo?
Gist doesn't allow folders

**Comment by sudocanttype** [comment]
How should we implement adding "div.XcVN5d" back to rich? Should we just make a new PR, or just manually edit it in?

**Comment by colonvirus** [comment]
Make a quick pr, and then we won't allow any more prs till we sort everything.

**Comment by Bugswriter** [comment]
PR

**Comment by sudocanttype** [comment]
ok, making a pr

**Comment by sudocanttype** [comment]
its #99
